### ISSUE TITLE
Use of CC PartValitadion in our Contracts (Lunar Landing, Space Station for example)

### ISSUE THREAD

**Issue by Brummi1234** [KSP-RO/RP-1#1068]
As discussed on Discord we could use something like:

PARAMETER
		{
			name = Avionics
			type = PartValidation
			partModule = ModuleAvionics
			minCount = 1
			title = Have control over your Lander
			hideChildren = true
		}

to check for certain modules in the contracts.
We can even check for ModuleTag*something* type Modules which are already used to mark parts for a some thing or another.

One use could be stopping super early lunar landings or stop people using capsules for space stations.

**Comment by siimav** [comment]
PartModule and part tags added in dc0002eb390306610160e98b37c20db04e8336b9, still need to update all the contracts though.

**Comment by siimav** [comment]
Solved this by utilizing crew science in station contracts.
