### ISSUE TITLE
Ideas for Improving Space Stations 

### ISSUE THREAD

**Issue by Teykn** [KSP-RO/RP-1#1356]
(Note, this is an "Issue" thread that composes of ideas that I have. Feel free to criticize and/or add any ideas in this thread.)

**Introduction:**
In a typical successful RP-0 career, people reach and complete the Moon Boots Contract (First Manned Lunar Landing). After this, though, most players experience some stagnation, as they typically set their eyes on sending kerbals to Mars. 
The intermediate that's between Moon Boots and Mars Boots are Space Stations. There are quite few Station Contracts however (3, alongside 5 resupply/addition contracts), which is only one of the problems.
Stations serve very little purpose as well, only serving as a mid-to-long duration space habitat used to generate small amount of funds via contracts, where more funds can be earned more interestingly via lunar landing missions. They're not useful for science either, because of a lack of station experiments (in ROKerbalism), a large presence of science in other areas (other planets and moons), and the "science snowball" doesn't necessitate stations at all.
Lastly, people don't seem to find Space Stations as interesting as other major missions/contracts that are done. Examples include: lunar probes, interplanetary probes, and manned lunar missions. It could be argued that Stations are only slightly more interesting then Commercial Satellite Contracts.

**Some Proposals/Ideas:**
Here are some of the ideas that I have for improving Space Stations, and possibly improving other areas as well.

1. Add a LOT more experiments to be done on Space Stations. 
ROKerbalism only has experiments up to the Mature Capsules node, and there's a limited amount that can be done too (4 in Mercury, 12 in gemini, and 5 in Apollo, iirc.). Skylab, for example, has **75 experiments**, not including the student experiments. This would solve 2 of 3 problems related to science I listed above, and it does not help solve the "science snowball" problem. Rather, it'd actually contribute to it. 
_Currently I am working on finding information about the experiments done on Skylab, and after that I'll look into other space stations if possible (Salyut, Mir, and ISS)._

2. Introduce Experiment-locking for Tech Tree Nodes and Contracts.
Currently, the science snowball is a problem that has sparked some discussion. Some have questioned why science from measuring orbital perturbations (or any other unrelated experiment) can be used in engine nodes (or any other unrelated tech line), for example. Overall, the sci snowball pushes people towards rushing and being risky, rather than realistic approaches done IRL.
What I'm proposing is for nodes and contracts to be able to be locked behind science experiments (if possible). For example, locking the basicCapsules node behind the Geiger-Muller radiation experiment. Another example would be locking manned interplanetary contracts behind crewed medical experiments on a _Space Station._ This would slow down the snowball, and provide a necessity to do specific experiments. This provides a realistic approach as well, since people IRL would like to understand the effects of long-duration manned missions before sending people to Mars.
_I have been told that this is possible via CC, but I have 0 experience with CC, so I will likely tinker around with that soon._ 

3. Add more Space Station Contracts.
Currently, the 3 "main" Space Station contracts are all related to areas that humans have or wish to go to (Earth, the Moon, and Mars). The problem with only having one contract for each celestial body is that it does not incentivize players to improve their stations, and there is no incentive to make more stations. Additional Space Station contracts that should be added should be based off of real life Space Stations, the modules they had, the crew duration, and other miscellaneous details. Contracts based off of Proposed Space Stations can also work.
The current First Space Station Contract works fine, being a contract that's based off of MOL (from what I can tell). What could come after is a more advanced "Second Generation Space Station" Contract based off of Skylab and Salyut, which have a science-experiment completion requirement, a crew requirement of 3 people, and a longer duration stay of either 60 or 90 days. Since there were multiple Salyut Stations, 2nd Gen SS contract should be able to be repeated. 
The last Earth-based Station that should come after 2nd Gen SS should be a Modular Space Station based off of Mir and the ISS. This would involve a contract series, with some contracts to bring specific modules/parts (Solar Panels, Radiators, structural parts, habitats, etc.). Other contracts would involve science, including a contract/experiment based off of Scott Kelly's Year-long stay in space. 

I'm not that good with coming up with contract ideas, but this is what I could think of. I understand that the contracts still seem mundane. The Lunar and Martian Space stations though, I believe they should be locked behind the 3rd generation SS contract series, since we have yet to put a station around the moon.

Anyways, I hope you guys are open to the ideas that I proposed here. I'm interested in seeing an improvement to Space Stations, and I'd like to contribute if possible.

**Comment by ec429** [comment]
I like these ideas.  Regarding (2), we already have some contracts that require experiments — look at FSO — so it shouldn't be too hard to add a "gather 360 days of station-medical-science" contract to gate manned-IP behind.
Currently the main driver for stations is the crew endurance records, which push towards keeping a single expedition there as long as possible and then ignoring the station after that; station experiments with long durations (of which medical is one) would tilt towards regular crew rotations over the long term, which is good.
Another contract idea: continuous habitation records.  Assuming that the current endurance records are meant to be individual crew, it would be good to have separate records for keeping a station crewed continuously across rotations.  But we'd probably need to fix a bunch of CC bugs to make _either_ kind of duration record work properly; currently they appear to calculate from the date the first crew reached the station even if they went home immediately afterwards :(

**Comment by Teykn** [comment]
Hmm, so thinking about the order of the contracts based off of what you said SNF, should be like this?:

Earth-based Station progress:
- 1st SS -> 2nd Gen SS (can be repeated 5 times, with durations being: 30-60-60-90-90 days?) -> 3rd Gen/Modular SS contract series 
Lunar-based Station progress:
- 2nd Gen SS -> 1st Lunar SS -> 2nd Gen LSS  (same duration/repeatability as 2nd Gen SS?)
- 3rd Gen/Modular SS series -> 3rd Gen/Modular LSS series (something like the proposed Lunar Gateway that expands into a "Lunar ISS" of sorts?)

Interplanetary is a weird area to tackle, since there were some proposals that came way before the flight of Skylab, and in modern times NASA and other space agencies (i think) are trying to understand the effects of long-duration space flight.

Since I suspect that Earth-based and Lunar-based stations would take quite a while, I'd be inclined to have this contract progress:
- 2nd Gen LSS -> Manned Venus flyby
- 3rd Gen/Modular SS -> Manned Mars flyby -> Manned Mars Orbit & 1st Gen Mars SS

I'm not including Manned Mars Landing into this proposed contract path, since I think that would have to be based on the "Surface Outpost" Contract group, and not the "Space Station" Contract group.

Thoughts? I'm still trying to think of how to get science experiments to be a part of more of these contracts.

**Comment by Elouda** [comment]
I'm not sure the flybys should be directly tied to the stations, or at the least not to the lunar ones if so.

**Comment by 7ranceaddic7** [comment]
I don't know if you all are wanting this level of depth, but here's a wrinkle for station progressions ...

Before you get any advanced "Space" station items useful beyond low-orbit, ya gotta prove you can do it ... on the ground .. at home.

Think contracts for HabStudies.

https://en.wikipedia.org/wiki/Desert_Research_and_Technology_Studies#/media/File:Habitat_Demonstration_Unit_(2010)_cropped_androtated.jpg

https://en.wikipedia.org/wiki/Desert_Research_and_Technology_Studies#/media/File:Habitat_Demonstration_Unit_with_X-hab_-_D-RATS_2011.jpg

**Comment by Teykn** [comment]
@Elouda How come? My reasoning for tying Interplanetary flybys to the lunar stations was because it would be unreasonable to send astronauts to venus or mars to be exposed to solar radiation for over 180d before subjecting astronauts to a long stay around the moon. What do you suggest if they shouldn't be tied to the proposed lunar station contracts?

@7ranceaddic7 I would assume the Space Station parts are tested on the ground when you're researching the nodes. Engines in game are treated as being ground tested before being flown on an actual rocket, so why not the SS parts? Seems excessive do go to THAT level of depth.

**Comment by 7ranceaddic7** [comment]
> Engines in-game are treated as being ground tested before being flown on an actual rocket

Not in a [TestFlight](https://github.com/KSP-RO/TestFlight) install.

**Comment by Bornholio** [comment]
yes in a testflight install, TF and TL use inflight failure data from real flights when possible

**Comment by TNT599** [comment]
I believe this would be cool if 3rd gen had high rewards to make the station ie like 500k reward 100k Advance to make it worth it especially around the moon. If the numbers seem to much or to little they can be changed but I would not make a 3rd gen if I had to spend 500k but only got 300k for example.

**Comment by Teykn** [comment]
I'll probably toy around with making some of these contracts. Not sure how I'd price them though. For 2nd gen Earth stations, I'd probably have their advances and rewards be significantly lower than the First SS contract, but with a decent amount of repeatability to reflect Salyut. 3rd gen, which I'm basing off of the ISS, should likely have a higher advance/reward.

Moon stations, I'll have to see as well. Since, irl, interest in the moon died out post-Apollo 11, they likely won't have very lucrative advances/rewards.

Changes will have to be made to the SS Supply Contracts as well, as I don't think there were plans to add additional modules to MOL, Skylab, nor Salyut.

**Comment by norcalplanner** [comment]
IIRC one of the planned preliminary steps irl for the manned Venus flyby mission was to test the hardware in high orbit around earth. Perhaps manned interplanetary missions could be gated behind a 180-day or longer station mission in high earth orbit.

**Comment by Teykn** [comment]
Well, I’ve started putting my ideas into contract .cfg files. Still want some feedback for some aspects though.

“Finished” adjusting the FSS contract, and made an “Improved Space Station” contract, with 3 contracts for crewing it: 30d, 60d, and 90d (2 completions possible for 60d and 90d). Gonna hold off on a “Modular Space Station” contract for now.

For the Lunar Station contracts, I’ve been thinking about it. Considering that I set it so you can start lunar contracts after Improved Space Station (and some of its crew contracts), I’ve decided to just have 2 main contracts: Lunar Space Station, and Modular Space Station.

I am having some trouble thinking of how a lunar space station could be used though. I’ve thought of (and partially made) a contract where you rendezvous a lander and the crew separately, but I’m not sure of other applications besides that. Any ideas? (Will also add some crew stay contracts as well).

**Comment by siimav** [comment]
Closing this since it predated Programs and many of the ideas have already been implemented in the new Early Stations program.
