### ISSUE TITLE
Astronaut complex upgrade speeds in progress training too much

### ISSUE THREAD

**Issue by Leitk** [KSP-RO/RP-1#1401]
If the astronaut complex finishes an upgrade while astronauts are in training, they get the benefit of faster training for the full course.
I had astronauts with end times of about a month out, but when the complex finished upgrading, they finished training almost immediately (I think the day had to complete, but it was less than one day).

This is a bit of an edge case, and minor.

**Comment by siimav** [comment]
Behaves as it should now.
