### ISSUE TITLE
Oddity: We have other jets Why no historical ramjets?

### ISSUE THREAD

**Issue by aazard** [KSP-RO/RP-1#1541]
Hello, its Aazard.

`- preface: either way I have some specs/data, if there is an individual that collects/archives such things`

I did open a PR before, maybe that  jumped the gun?

I will ask cleanly:

"Why was the choice made to not include AJE ramjets?"

Was it a "IRL RO" pacing/gameplay decision (low aircraft/spaceplane focus)? or a lack of "solid data" 
Is there any interest, past my own, in adding ramjets into the game.tech tree?

esp seeing AJE has a ramjet "setting" and although a little hard to find, data on production ramjets as early as 1942: some Dr Sanger units (SK P.1040) and the Kayaba Model 1 (NE 0 and NE 0a), exists (and I logged it)

I can detail my reasons for thinking they are a positive addition, if you are interested (trying to avoid essay length)

On that note I did compile a few bits of data with sources on various units that may be of interest.
In my fashion these notes/sources are somewhat lengthy (but useful irl data is inside)

I am sorry if my issue/pr on topic was too early and "multi focused". 
The topic I had the most focus on was the ramjets so I will hope for a reply

**Comment by adouge** [comment]
I for one would much like to see ramjets
although their availability may mean the X-plane contracts would need tweaking / rebalancing

**Comment by siimav** [comment]
Plenty added in #2332

**Comment by aazard** [comment]
wonderful, thank you
