### ISSUE TITLE
Display the total cost of a vehicle in the VAB KCT window

### ISSUE THREAD

**Issue by StonesmileGit** [KSP-RO/RP-1#1543]
Currently you manually have to calculate the total cost from the separate values displayed in the VAB

**Comment by siimav** [comment]
PLC shows rollout cost but integration isn't there any longer. Getting the total cost is even more complicated now since you would need to factor in both the maintenance for LC and engineer salaries.

**Comment by NathanKell** [comment]
Fixed to show integration salary cost estimate again. Total cost is less clear.
