### ISSUE TITLE
Inconsistent placement of engines and their upgrades

### ISSUE THREAD

**Issue by Lycowolf** [KSP-RO/RP-1#1558]
Viking 5C upgrade is unlocked in 1962 node, but the engine itself is available at 1965.

There are some engines that have unlockable upgrades, but the engine itself is not available at all:
 - 1965: Vexin engine upgrade: Vexin config
 - 1970-1971: Vexin engine: Valois config
 - 2004-2008: Vikas engine: Vikas-1+ and Vikas 2, Aestus engine: AestusMod config, Kestrel engine: Kestrel-2 config
probably more.

**Comment by Capkirk123** [comment]
I probably fixed that when I redid the Viking configs.
