### ISSUE TITLE
Implement interpolation of time estimate until research is complete

### ISSUE THREAD

**Issue by StonesmileGit** [KSP-RO/RP-1#1564]
If no interpolation is done, the time displayed will always be too long.

Something simple like assuming average speed of the current speed and the speed at the time when it would be finished might be enough.

**Comment by NathanKell** [comment]
Oh this is because everything is estimated based on the current-date HOI modifier?

**Comment by StonesmileGit** [comment]
Correct. It likely doesn't change the time estimate for the current research much, but might be quite noticeable for items in the queue

**Comment by NathanKell** [comment]
Fixed in PLC.
