### ISSUE TITLE
Maintenance cost for tooling

### ISSUE THREAD

**Issue by siimav** [KSP-RO/RP-1#1568]
Add per-tooling maintenance fees and an option to discard unneeded tooling types.

**Comment by StonesmileGit** [comment]
This should probably include a reduction in the normal maintenance cost, to compensate

**Comment by NathanKell** [comment]
I have insufficient :+1: to express my approval.

**Comment by NathanKell** [comment]
Rather than doing this halfway thing, we'll just do actual manufacturing, I think, since we really need it and it supersedes this.
