### ISSUE TITLE
Can't spend KCT upgrade points in VAB in Flight Scene

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/RP-1#1569]
The "Upgrades" button got enabled in the flight scene recently-ish, but the buttons to spend points on VAB lines are missing:

![Screen Shot 2021-10-14 at 15 54 45](https://user-images.githubusercontent.com/5061230/137387327-4b4290a0-249f-410c-bc53-5d9d6b4b5318.png)

R&D tab's button is fine, however.

(from [discord](https://discord.com/channels/319857228905447436/620690446540341261/898298029369602080))

**Comment by siimav** [comment]
No longer relevant.
