### ISSUE TITLE
Enhancements For Space Stations

### ISSUE THREAD

**Issue by zephyrspace** [KSP-RO/RP-1#1615]
Introduction
=========

Currently there is very little point to space stations beyond having a place to store your kerbals/orbital assembly projects before throwing them at the moon/mars.

This is very different to IRL where early space stations such as the US Skylab and the Soviet Salyut/Almaz gave scientists and engineers their first view of the realities of long duration crew habitation as well as a test platform for longer duration experiments which needed human oversight. These morphed into modular space stations such as MIR and the ISS which provided a long term base of operations and enabled third parties access to laboratories and facilities in low earth orbit.

This issue aims to track the progress of modeling these activities in RP-1, which also provides the player a real world pathway to follow post-crewed lunar landing

Roadmap
========

Definite Aims
------------------
- Add "generic" crew science to space stations
  - Add a new consumable resource "research payload" that is consumed by space stations to simulate the running and depletion of experiments
  - Add a new process to convert "research payload" into "processed payload" to simulate the running of third party experiments on later space stations
  -  Provide an incentive to build modular space stations with the aim of guiding the player towards permanent crewed space occupation.
- Add contracts that support/direct the player through the 70s/80s in a similar way that current RP-1 contracts do for the 50s/60s
  - Commercial Science Contracts (Take X units of research payload to station Y and optionally? return Z units of processed payload after W days)
  - Payload specialist contracts (Take a "loaned" scientist up to your station with one of your crews for X days, maybe with optional payload requirements)
  - "Tourism" contracts (Take a "tourist" up to your station for a crew rotation)

Possible Aims
-------------------
- Add experiment parts that need to be deployed by crew and need scientists on board to function (Skylab solar observatory, Almaz earth observation, etc)
  - Example Experiments:
    - Skylab ocean observation (biome specific/should need a scientist to run/engineer to deploy) (suggested by Alex6511 on discord) 
  - As such experiments are added to certain era's the "generic" science payload should be decreased by an equal amount.
- Add contracts to design a module to spec for your "ISS" and send an entirely loaned crew up there to simulate international cooperation

Notes
====
Related to #1613 in that both of these aim to provide a "branch" of progression post crewed lunar landing. Also would be happy for suggestions/refinement of these aims to add what other people think are missing from this aspect of game-play.

Initial Station Science Numbers
-----------------------------------------
Station Science Tier | Example Craft | Total Duration (d) | Pressurised Volume (m^3) Min |  | Expected Launches For Full Science | | Resource Usage (kg/hr) | Total Resources at Tier (T) | Total Science
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- 
  |   |   | Min | Max | Min | Max |   |   |  
T1 | Salyut 1-5, Skylab | 200 | 100 | 350 | 4 | 1 | 1 | 4.8 | 480
T2 | Salyut 6/7, Spacelab+Shuttle | 1460 | 90 | 140 | 2 | 1.29 | 1 | 35.04 | 3504
T3 | MIR, ISS | 10037.5 | 350 | 915 | 3 | 1 | 1 | 240.9 | 24090

**Comment by zephyrspace** [comment]
Contract Timeline
------------------------
The following set of contracts aim to guide the player from having no permanent space presence (space station prototypes) to hopefully the international cooperation era. Not every play-through style should be able to complete all the contracts if following strictly historically but they should still be able to do one of each contract. **VERY WIP:** *feedback greatly appreciated, esp w.r.t gating contracts*

### Phase 1 (Space Station Development)
- Contract: Launch Space Station 
  - repeatable x5
  - these simulate the salyut program almost 1-1
  -  the US only launches 1 station
- Contract: Send Crew Up to Existing Space Station 
  - repeatable all tiers but with scaling crew count

### Gating mission? (Apollo-Soyuz test program)
- This doesn't really fit here but it's too cool an idea not to note down
- target spacecraft will be up during a time window
- rendezvous and dock with it
- TODO: See if it's possible to use the same system that stock uses for "rescue missions" to send up a "spacecraft"
  - maybe using one of those weird capsules like Mk3/advanced capsule?
- APAS 75 docking port needed
- Bring an adaptor!
- Stay Docked for 1 day/X orbits
- Return _your_ crew safely, see if it's possible to

### Phase 2 (Second Generation Space Stations)
- Technically only the Salyut 6/7 stations counted for second gen stations
  - but the US could just launch skylab 2?
  - or stick another port onto skylab1 before sending it up?
- More than one docking port to allow for resupply missions
- Contract: First second generation space station 
  - 2 docking ports
  - 60d crew rotation
  - 1 resupply mission
- Contract: Send Resupply Mission to Existing Space Station 
  - Food+Water?+O2?+Payload
  - what about people using fuel cells + lox->gox converters?

### Gating Contract (6 month crew duration)
- Simply enough, send a crew of at least two to a station
- And keep them there for 6 months
- Originally done on the salyut 6
- TODO: Can this even be done w.r.t kerbalism stress on an RN salyut?

### Phase 3 (Modular Space Stations)
- Contract: Visiting Scientist 
  - 1 loaned crew 
  - X units of payload
  - Y days
  - gives sci + minor funds rewards
- Contract: Commercial Crew Rotation 
  - Send X loaned crew up for y days
  - how does loaned crew work with the RP-1 proficiency system
  - gives sci+funds reward
- Contract: Commercial Cargo 
  - Send X units of payload up for Y days and bring Z units of processed payload down
  - Gives sci+funds reward
- Contract: Add module
  - launch module according to spec (EC/Crew cap/Experiments/Docking port types?)
    - Possibly "We put a module in orbit, plz attach to station?" (Possibly use the same system that stock has for "lost" spacecraft rescues)
  - possible send loaned crew up to the "new module", just send to station but after the module is placed
- Contract: Tourism
  - literally the tourist contracts from stock but with greatly increased risk of failure

### Phase 4 (ISS/Permanent Habitation Era TBD)

**Comment by siimav** [comment]
I guess we still need to implement a Modular Stations program but we probably need to rethink how to implement that based on how the new Early Stations program works.

**Comment by KenDaveRob** [comment]
@zephyrspace / @siimav I am having a very hard time figuring out how the research labs are supposed to work in rp-1.  The research payload doesn't seem to drain when research is going on (nor does actual science get created).  So far the only thing that kind of works is the skylab, which does seem to be able to convert film data into transmittable science.  I have looked online for some guides on the subject but it seems like very few RP-1 players have tried this program.  More information on the current state of this program would be very helpful.
