### ISSUE TITLE
Refurbish engines on the launch pad.

### ISSUE THREAD

**Issue by Alex6511** [KSP-RO/RP-1#1638]
In the event of a launch ignition failure, you are currently forced to roll your entire stack back to the VAB and back out again. This incurs a time delay, but is generally seen as a balanced interaction.

In the event of a launch _performance_ penalty, you are currently forced to roll your entire stack back to the VAB and swap the engine. This incurs a edit, time, and cost delay (though the amount is less because it is an engine refurb). Additionally, if one is not informed of how this works and only edits the craft or rolls it back out again without editing, like the ignition failure procedure, the engine will not display as performance degraded in the UI, both in the staging list or in the PAW outside of its raw thrust output numbers. This is some unclear UX that hides the fact that the engine is degraded.

A preferable solution to both of these would be a button in KCT when the craft is on the pad that allows the removal of all engine anomalies in exchange for a time delay and some factor of original engine cost. This would reduce scene transitions and the need for rolling back to the VAB, as pad swaps on engines are possible. This button should validate that launch clamps are still attached.

**Comment by siimav** [comment]
Implemented in #2327
