### ISSUE TITLE
[Idea] Mastering by industry: the concept of new mechanics on top of tooling

### ISSUE THREAD

**Issue by VeselyiKot** [KSP-RO/RP-1#1700]
The current tooling mechanics, in general, fulfills its task, but... But it doesn't correspond to reality in the slightest. This proposal is aimed at eliminating this shortcoming, while keeping the game fun and easy-to-learn.

It proposes the division of tooling into two separate mechanics: tooling itself (without changes in price and mechanics) and "mastering by industry".
In the proposed change, **tooling does not give an instant effect at all**.
Instead, it _makes it possible_ to reduce the cost and speed up the production of the tooled part with each subsequent similar part, according to a formula close to hyperbole, where the speed and price equal to the current for the tooled part are achieved after [BALANCE] of the produced parts, but even after that each next still becomes faster and cheaper in production (yes, cheaper than currently), but with each subsequent time for a lower value (with like "CurrentTooled-25%" after about 100 parts produced, let's say).

•••

### From a realistic point of view:
Actually, the first few parts are prototype/pre-production ones, crafted for testing. They are created almost manually by engineers, plus add on top tests and tests, static and dynamic ones needed for first ones, consuming both time and money. It's long and expensive, it was so in history, so it should be in the game (fortunately we have timewarp, so that would not be a gameplay issue).
The subsequent ones are an early series. No longer so long and not so expensive, but still tangible.
After [BALANCE] parts there is mass production, and here — the more produced, the cheaper and faster it becomes: the masters tool their hands, logistics is honed, production optimising experts come into action...

Non-tooled part, respectively, is a piece product, created manually by engineers with five-digit salaries. 
The price tag and the time spent are appropriate (that is, the same as now for untooled parts, without changes).

•••

### Addressing current problems
From gameplay perspective, this proposal is aimed at correcting three problems at once (both gameplay and realism/immersion/simulation ones) of the current mechanics:

1) At the moment, there is not the slightest sense, for example, to improve the R-7 family throughout the game by adding new upper stages and upgrading existing engines, but without touching what has already been done. At the moment, it is always cheaper and more efficient to upgrade the rocket, replace the engine, stretch the tank in the same diameter, or even make new one from scratch...
 In the new mechanics, the player will have a reason to use ancient, outdated, less effective, but perfectly mastered in production technologies. Yes, it is a three-hundred-ton monster from the fifties, but after three hundred launches it costs almost the same and is assembled as quickly as the newest rocket, which can do the same in half the mass.
**This will reward a player who can, wants and knows how to think for the future**, but also will not offend a lover of new products (who will get a lighter, more efficient and cheaper rocket in the slightly longer term, but will fall behind schedule and take some serious expenses _right now_).

2) At the moment, it also makes no sense to design a rocket of the Saturn 1 type, with a bundle of small diameter tanks. In the new mechanics — yes, it is monstrously inefficient by weight, but the tanks have been successfully mastered by industry, are cheap and fast in production. Yes, as a whole it is still expensive, yes, the design is unperspective, but **the "Saturn-1-esque" rocket can be built quickly "here and now"** without waiting for the "acceleration" of production. 

3) At the moment, **a player with a lot of money can insta-tool any rocket**, and immediately start its production, quickly and cheaply. This is unrealistic, and in the new mechanics, the first few prouced rockets also naturally have to spend a lot of money and time to work out the design, perform static tests and similar things, almost as if they would be untooled at all, instead of instant cost/time halving.

•••

### From the point of view of game design:
At the moment, the player's progression rate is balanced through economy system and production rate multipliers.
To me, this approach seems to be a dead end and generates hordes of caveman experts flying into orbit during first year.
The proposed change will slow down the initial progress to a certain extent and slightly accelerate subsequent milestones of cosmonautics, such as the mass launch of satellites.
It would also allow to perform some history accurate stuff, like dozens of early, unsuccessful interplanetary probes on rapidly produced rockets, bringing the schedule closer to the historical one with certain settings of the "mastering by industry" curve.

It will also make, from a certain point on, engine failures and mission failures less tragic and less provoking to return to launch. And can make the entire space program more realistic if someone would also implement probe/electronics failures.

•••

### Not only tanks
In addition, the mechanics of "mastering by industry" can be applied to some other parts of the rocket, such as engines.
It is logical that a large production scale engine, like RD—107/108, should be not only more reliable on the hundredth unit, but also cheaper than the first, and we already have a suitable cost multiplier system for implementing this.
Raise the prices of all engines, for example, five times, and the current price should be achievable after [BALANCE] units produced; further you are in production, the faster it is, the cheaper it is. 
Engine suggestion addresses the same problem of "in RP-1 it makes no sense to produce R-7 from 1957 to 2022", and is pretty realistic.

P.S. Yes, this will require a reworking of the game balance and economy, but it seems to me that the advantages outweigh.
P.S.2. Yes, I know my English is bad. I can't help it.

**Comment by NathanKell** [comment]
This is part of a manufacturing system, which is forthcoming.
