### ISSUE TITLE
Freeze bug during loading or resuming save

### ISSUE THREAD

**Issue by byt3c** [KSP-RO/RP-1#1804]
There is infinite loop issue. I updated new design started to rebuild launchpad to include more fuels for 3km downrange, and now game freezes on save load. There is sound- birds chrip as in KSC but game is frozen, nothing on display. Repeats every time i want to load save. no errors in log. save in attachment.
[RP2.zip](https://github.com/KSP-RO/RP-0/files/9731508/RP2.zip)

[KSP.zip](https://github.com/KSP-RO/RP-0/files/9731532/KSP.zip)

**Comment by siimav** [comment]
Hopefully no longer happening?
