### ISSUE TITLE
ProcAvi log spam after vessel breaks on launch attempt

### ISSUE THREAD

**Issue by Gordon-Dry** [KSP-RO/RP-1#1807]
After the vessel broke apart for some reason (I guess dynamic pressure issue at a cone shaped avionics part on top of the first stage) the avionics and a chute part from the top are still alive and in focus, the log is spammed with
```
[LOG 17:19:58.771] [ProcAvi] RefreshDisplays() Controllable mass: 0, mass: 33.00kg cost: 6, Utilization: 47.1%
[LOG 17:19:58.771] [ProcAvi] RefreshDisplays() Controllable mass: 19, mass: 427.1kg cost: 333, Utilization: 39.4%

```
always the same numbers.
[KSP.zip](https://github.com/KSP-RO/RP-0/files/9741913/KSP.zip)

**Comment by siimav** [comment]
I'm just going to assume that this got fixed with the recent changes to ROT-PP-ProcAvi integration.
