### ISSUE TITLE
KCT Merge free money

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/RP-1#1843]
Start with negative funds and 2 built vessels in KCT storage.
Edit one vessel, Merge the other into it
Click Save
- "not enough funds" message is shown (good? not sure what it needed funds for)
- edit session doesn't end (good)
- funds have increased, are now positive (bad)

Clicking Save again works, since funds aren't negative (making it easy to miss the bug if you didn't notice the message and thought you just misclicked)

before:
<img width="274" alt="Screenshot 2022-12-03 at 23 19 39" src="https://user-images.githubusercontent.com/5061230/205474364-35825c2d-4547-4b56-b262-ed6e5c80a96b.png">

after:
<img width="271" alt="Screenshot 2022-12-03 at 23 19 51" src="https://user-images.githubusercontent.com/5061230/205474367-0e298a99-6908-420e-95de-e43e8630c3f0.png">

**Comment by NathanKell** [comment]
Merge is dead in PLC.
