### ISSUE TITLE
Crash, crash and another crash after Realistic Progression One (RP-1) Express Instal

### ISSUE THREAD

**Issue by undivido** [KSP-RO/RP-1#1873]
Did according to the instructions.
I chose version 1.12.3 in the steam, updated it, copied it completely to a separate folder and deleted all old saves and mods.
Launched CKAN, selected a location for KSP 1.12.3, and ran the Realistic Progression One (RP-1) express installer.
I agreed with all the suggestions and after finishing launched KSP.
The game took a very long time to launch and eventually crashed.
I killed the process and restarted the game.
This time it loaded faster, but at the end the game crashed. And so every time at startup everything is loaded and at the end it crashes.
[KSP.log](https://github.com/KSP-RO/RP-0/files/10470190/KSP.log)

**Comment by undivido** [comment]
![image](https://user-images.githubusercontent.com/56364085/213804212-f940c9f3-c392-4e2b-9920-6bfc46069ad5.png)
[mod_list.txt](https://github.com/KSP-RO/RP-0/files/10470228/mod_list.txt)

**Comment by Test-Account-KSP** [comment]
High res graphics are unlikely to work with 16 Mb ram, try medium res

**Comment by undivido** [comment]
> High res graphics are unlikely to work with 16 Mb ram, try medium res
But here it is written that from 16GB you can choose high - https://github.com/KSP-RO/RP-0/wiki/RO-&-RP-1-Express-Installation-for-1.12.3
![image](https://user-images.githubusercontent.com/56364085/213807338-a2f30345-689c-4ae6-9c11-674acc4b6c8a.png)

I'll try the medium

**Comment by Test-Account-KSP** [comment]
Looks like it's no longer correct with Parallax 2.0

**Comment by undivido** [comment]
I completely uninstalled all mods and reinstalled again, choosing medium quality and... same result
It can be seen that the memory allocation is not even close to the maximum
![image](https://user-images.githubusercontent.com/56364085/213810967-a443c913-bb09-4c42-90e3-d50a51992abf.png)
[KSP.log](https://github.com/KSP-RO/RP-0/files/10470487/KSP.log)
[mod_list_medium.txt](https://github.com/KSP-RO/RP-0/files/10470493/mod_list_medium.txt)

**Comment by Test-Account-KSP** [comment]
Wonder what is going on in the log here
[LOG 00:49:16.835] [OD] Adding for body Titan map named  of path = RSS-Textures/PluginData/TitanHeight.dds
[LOG 00:49:16.837] [OD] Adding for body Titan map named  of path = RSS-Textures/PluginData/TitanColor.dds
[LOG 00:49:16.858] [OD] --> OnDemandStorage.EnableBody loading Titan
[LOG 00:49:17.226] [OD] ---> Map RSS-Textures/PluginData/TitanColor.dds enabling self. Path = RSS-Textures/PluginData/TitanColor.dds
[LOG 00:49:17.435] [OD] ---> Map RSS-Textures/PluginData/TitanHeight.dds enabling self. Path = RSS-Textures/PluginData/TitanHeight.dds
[WRN 00:49:17.445] Cannot find preset 'High' for pqs 'Titan'
[WRN 00:49:17.446] CelestialBodyTransform: Cannot find CelestialBody.

**Comment by Test-Account-KSP** [comment]
So Kopernicus fails to modify the system because it's unable to find the correct textures. No idea why it happens ((

**Comment by marsh1832** [comment]
Is this an external drive? If so they are known to cause texture issues

**Comment by undivido** [comment]
> Is this an external drive? If so they are known to cause texture issues

No, internal NVMe

**Comment by SimonSays6224** [comment]
I'm having this same issue

**Comment by siimav** [comment]
Looks like a memory-related issue. The thing to keep is mind is that the game will also use large amounts of page file for both 16 and 32GB of RAM. So if page file size is intentionally limited or the drive it is on has insufficient free space, then crashes are likely to happen.
