### ISSUE TITLE
You can lock yourself out of some low res ScanSat contracts, and I think there is easy fix.

### ISSUE THREAD

**Issue by cola98765** [KSP-RO/RP-1#1898]
There are those contracts for 25% altimetry survey, AND you require them to unlock 80% contract.
Currently if you forget to get the first contract before you hit 15% you are locked out of doing the 80% contract for given planet.

Solution 1: 
If I were to just increase the `maxCoverage` requirement, the contract would just reappear becasue `maxCompletions` is set to 0, and I think it would work when set to 1.

Solution 2:
Scanning the planet and then getting the contract might not be intended solution, so if I were to remove the 25% **contract** requirement from 80% contract and replaced it with 25% minCoverage, I think the progress would remain the same, but you would no longer be locked out of 80% contract.

**Comment by siimav** [comment]
Since PLC no longer has ScanSat contracts, I guess the issue no longer exists either. :)
