### ISSUE TITLE
Space Station Programs

### ISSUE THREAD

**Issue by zephyrspace** [KSP-RO/RP-1#1953]
# Space Station Programs
A summary of the discord discussions on `#programs_and_lc`. And a sketch of the space station programs.

# Extended Space Habitation (Meant to mimic salyuts 1-5)
* Requirements: Crewed Orbit Program
* Duration: (Regular) 6 years
* Funds/Year: TBD
* Objectives:
  - 30 day crewed space record
  - 60 day crewed space record (salyut 4 was not messing about)
  - launch prototype space station x5
  - send crew to space station (maybe have the crew requirement be another part of the launch prototype station contract? and enforce deorbits so people stop reusing tin cans in space?)

# Improved Space Habitation (Skylab/Salyuts 6+7)
* Requirements: Crewed Moon Landing or Extended Space Habitiation
* Duration: (Regular) 10 years
* Funds/Year: TBD
* Objectives:
  - 90 day crewed space record (skylab 4 was 84 but im rounding)
  - 180 day crewed space record (salyut 7's record was ~240 but I'm still rounding)
  - launch improved space station (x1 required with follow ups being optional)
  - also includes some maneuvers as part of the contract
  - send crew up to improved space station (x3 required to match the min of skylab)
  - send resupply mission to improved space station (x3 but can be shared taken on the same vessel as the crew rotation)
  - send experiements to improved space station (x3 but can be ride shared, skylab and salyut had programs that allowed student experiments/guest crew)
  - alter station orbit (optional but a nice to have as that was a thing, wish there were force accepted contracts tho, maybe I can just bake the manuvers into the launch improved station contract?)

# Advanced Space Habitation (MIR/Literally nothing thanks space shuttle)
* Requirement: Extended Space Habituation
* Duration: (Normal) 15 Years
* Funds/Year: TBD
* Objectives:
  - Launch advanced space station core 
    - also includes some maneuvers as part of the contract
  - Launch Module
    - you need at least 1 of each module variant
    - Hab
      - light (just crew space)
      - heavy (more crew, an airlock, maybe a cupola)
    - Power Generation 
      - Solar
      - Nuclear
      - Fuel Cell
    - Lab
      - Crewed
      - Uncrewed
      - Greenhouse (thanks SSPXR)
    - Attitude and Propulsion
      - Attitude (at least 1 reaction wheel)
      - Propulsion (IIRC theres a way to get the delta v that a craft still has? Otherwise just making them have some generic thusters is probably the best we can do)
  - Launch Crew (There were 40 of these IRL, rip players I guess? Probably 20 is ok for required)
  - Launch Resupply (Progress craft were the main ones to mir, calling it x4 required but this is basically a mess at this point)
  - Dock "foreign module" (will need to kit bash basic modules/visiting craft out of proc parts but thankfully they wont need to survive reentry, see shuttle-mir)
  - Dock "foreign crew" (see Euromir, possible reuse of the tourist class from stock but rename them visitor)
  
# Continuous Space Habitation Era (ISS)
(TBD)

**Comment by siimav** [comment]
Don't believe this is particularly relevant any longer with the Stations program that got added recently.
