### ISSUE TITLE
Investigate rebalancing plane & Suborbital Research science

### ISSUE THREAD

**Issue by ppboyle** [KSP-RO/RP-1#1958]
Consider all the following changes:

Lower the plane science duration/total science available to both reduce the science gain and also make it less grindy.

Lower the film/bio/advanced bio duration but not decrease the science gain, so they're more amenable to being done with sounding rockets.

Have a capsule based experiment that subsumes/delivers the plane science, and also subsume supersonic science under hypersonic science, to make it possible to catch up that science during mercury.  Hypersonic science total would need to be bumped up by the (new) value of superaonic though to account for this change.
Eg supersonic- hypersonic - high hypersonic (capsule only) would become a Kerbalism science chain like visible imagine 1 and 2 are 

The goal here is to make no planes science gain reasonable without special code.

**Comment by pap1723** [comment]
Fixed with recent rebalancing changes
