### ISSUE TITLE
I installed RP-1 for 1.12.3(or whatever the newest version of RP-1 is I forgot) but when I loaded up KSP, it said there were 28 errors. I think I might've missed something when I read the installation tutorial, could someone please help me on this?

### ISSUE THREAD

**Issue by FurryDestroyer29** [KSP-RO/RP-1#1963]

**Comment by siimav** [comment]
https://github.com/KSP-RO/RP-0/wiki/RO-&-RP-1-Express-Installation-for-1.12.3
Did you follow this install guide? If you haven't done so already then it might be worth retrying a second time from scratch.

**Comment by FurryDestroyer29** [comment]
Uh I can try because now it loads but theres only a flag in the main build area for capsules and it was just to confusing so i deleted it. Was that part of the mod?

**Comment by siimav** [comment]
I'm not sure what you mean by *a flag*.
Either way, if you haven't managed to resolve all the issues in the meanwhile, then it's probably worth starting the install process from scratch for the 2.0 version of RP-1!
