### ISSUE TITLE
Probe Core loses avionics on vessel load

### ISSUE THREAD

**Issue by jenden0** [KSP-RO/RP-1#1970]
I'm running in to a strange problem with the avionics in my procedural probe core. I set it up with a controllable mass of 0.5t, which shows up correctly in the VAB. A glance at the save file also looks like it's set in the ModuleProceduralAvionics with "controllableMass = 0.5" in the KCTVessel. However upon loading the vessel up on the launchpad the conrollableMass (the UI display as well as in practice) drop to 0. The save file immediately after loading on the launchpad also shows controllableMass=0. 

I've launched a general variant of this rocket 3 times before, all of which worked normally. Then starting yesterday or today I've had two consecutive rockets (same design) with the same issue. I may have upgraded the TL of the deep space avionics from 0 to 1 between the working and broken rockets, but I don't have a great way to confirm that.

[Save file](https://drive.google.com/file/d/1hPad-FJoQF2yXpzalPXKHZ2Q0R9Nk-N8/view?usp=drive_link) before loading the rocket on the pad
[Save file](https://drive.google.com/file/d/1RRclf0859A_GfjlqFMP42WD8XuoduXk1/view?usp=sharing) from the pad after loading the rocket
[Log file](https://drive.google.com/file/d/19-yumech_8-6wHTYUGRqjgzHHRZlz6it/view?usp=sharing)
[Mod list](https://drive.google.com/file/d/13-Q1jZMrxKCp0-o6LVe7kpfTipKRzpy8/view?usp=sharing)

**Comment by siimav** [comment]
Thanks for the report. Fixed in 8498b8625c1d5db5575697410a00cd1b7894aaac
