### ISSUE TITLE
Building Plans & Construction Tooltips

### ISSUE THREAD

**Issue by pap1723** [KSP-RO/RP-1#1977]
When hovering over an available build plan, it should give a tooltip for the cost of the craft. There have been times where I am told I don't have enough funds, but cannot see how many I am short without having to scene switch into the VAB.

**Comment by pap1723** [comment]
Also, it doesn't reflect the current cost of the rocket. It reflects the cost of the rocket when you added it to a Build Plan. I added a rocket before I was able to afford the tooling, then despite having enough funds (after I tooled the rocket), the game still thinks I do not have enough.

**Comment by NathanKell** [comment]
Plans are just archived copies of the BLV at the time they were archived, they can't be dynamically updated for tooling changes or anything else that happens while they're "in the box" as it were. You'd have to load and resave them.
