### ISSUE TITLE
Express Install seems to want to install Legacy version 

### ISSUE THREAD

**Issue by hex4def6** [KSP-RO/RP-1#1986]
Selecting v2.0 of the "Realistic Progression One  (RP-1) Express Install" in CKAN results in the following mods being queued up:

![image](https://github.com/KSP-RO/RP-1/assets/518458/6681694c-f60d-4781-88c2-d1bda193503d)

However, I don't want the Legacy Version...

**Comment by NathanKell** [comment]
You either haven't updated CKAN to latest, or haven't refreshed CKAN metadata, or have existing mods installed. As the popup when starting Legacy RP-1 says, you have to completely uninstall your mods before you will be offered the new RP-1. (In particular, it is marked as incompatible with the older versions of many ROmods, to prevent using new-RP-1 with pre-savebreaking versions of those mods and having a broken experience. That means, however, that you have to uninstall _everything_ before you will be offered the choice for new RP-1.)

When in doubt, follow the Express Install guide to the letter (including making a clean KSP install).
