### ISSUE TITLE
Adjustable heat shield doesn't limit type

### ISSUE THREAD

**Issue by westlakem** [KSP-RO/RP-1#1991]
I just completed EDL R&D, unlocking the Adjustable heat shield.  I am able to adjust the slider all the way up to LunarHS even though I should only have access to heatsink technology.
![image](https://github.com/KSP-RO/RP-1/assets/4505074/83d73b20-4491-4908-8bfb-5fd33cf8a650)
![image](https://github.com/KSP-RO/RP-1/assets/4505074/5b588424-7de4-4810-ad2d-11298521d6ff)

**Comment by siimav** [comment]
But can you actually build the vessel with a config you haven't finished researching?

**Comment by westlakem** [comment]
Apparently not.
![image](https://github.com/KSP-RO/RP-1/assets/4505074/ad4deea9-2418-4f8e-a3ae-328e97a1e2f7)
I guess I would have expected the name to indicate that the same way the fuel tanks do
![image](https://github.com/KSP-RO/RP-1/assets/4505074/8a27eaab-5ebe-4a97-9492-98fec4adbe6a)

**Comment by pap1723** [comment]
Working as intended. When the text is Orange, it means you do not have it unlocked yet. Works the same way with the Tanks now

**Comment by pap1723** [comment]
Ah, I understand now.

**Comment by NathanKell** [comment]
That sounds like a ROHS issue then. It presumably doesn't have whatever code in RF makes those orange?

**Comment by siimav** [comment]
Implemented in https://github.com/KSP-RO/ROHeatshields/commit/bbf06053d1de0c5495884623efe894c70434d713
