### ISSUE TITLE
Repeatable optional satellite contracts are missing Confidence

### ISSUE THREAD

**Issue by FioraAeterna** [KSP-RO/RP-1#1993]
![image](https://github.com/KSP-RO/RP-1/assets/7761472/2d12f646-0e8e-4243-acce-5b3da4c54f51)

The other repeatable contracts I've seen give confidence, so I would assume these were meant to as well.

**Comment by FioraAeterna** [comment]
Also worth noting that the "Commercial Communications Satellite" seems to give less reward than "Communications Test Satellite", even though the former is more difficult:

![image](https://github.com/KSP-RO/RP-1/assets/7761472/283d0660-e892-4362-8a45-e26813186462)

![image](https://github.com/KSP-RO/RP-1/assets/7761472/9d97cd9c-0e6b-4325-8987-3f979fbae6ad)

**Comment by pap1723** [comment]
Fixed in previous update
