### ISSUE TITLE
Retirement dates seem to be going backwards

### ISSUE THREAD

**Issue by westlakem** [KSP-RO/RP-1#1995]
All of the leaders say they retire in 3652 days, however the leaders I have chosen... well...
![image](https://github.com/KSP-RO/RP-1/assets/4505074/8cb0268b-b4f8-482a-80db-c9c0ea1ed978)

**Comment by FioraAeterna** [comment]
I think the bug may be in /RP-1/tree/master/Source/Leaders/StrategyRP0.cs

RichTextUtil.TextParam(Localizer.Format("#rp0_Leaders_RetiresIn"), 
                            extendedInfo ? KSPUtil.PrintDateDelta(LongestDuration + KSPUtils.GetUT() - DateActivated, false, false)

I think the formula should be LongestDuration - KSPUtils.GetUT() + DateActivated.

**Comment by NathanKell** [comment]
Purely visual bug. And you're right on the formula change, though I didn't see your comment until after I fixed it. You can tell which mode (dates or deltas) _I_ play with, or I'd have seen that bug when I implemented this :D
