### ISSUE TITLE
Wiki download page has an issue, 1.12+1.8 are needed, not just 1.12

### ISSUE THREAD

**Issue by BobKermanIndustries** [KSP-RO/RP-1#2002]
For the express install 1.12 and 1.8 versions need to be selected in CKAN as KSP Wheel has 1.8 as max version.
![image](https://github.com/KSP-RO/RP-1/assets/108592192/e602c51c-b17d-4873-93d6-b0506a04432c)

**Comment by tedKarabeliov** [comment]
I also have the same issue. Max version is indeed 1.8 and it doesn't let me install express rp1
![image](https://github.com/KSP-RO/RP-1/assets/6270964/1af2cb70-c9b9-427d-b38a-e09392c78cd5)

**Comment by KEKKJ123** [comment]
> I also have the same issue. Max version is indeed 1.8 and it doesn't let me install express rp1我也有同样的问题。最高版本确实是 1.8，它不允许我安装 express rp1 ![image](https://github.com/KSP-RO/RP-1/assets/6270964/1af2cb70-c9b9-427d-b38a-e09392c78cd5)

Have you refreshed the metadata of CKAN? I have encountered a similar situation where simply refreshing the mod will display the correct version information.

**Comment by Clayell** [comment]
You may need to upgrade your CKAN as well, the older versions did not have auto-updating I believe.
