### ISSUE TITLE
Rep reward often so low for sounding rocket contracts that it's not worth launching more than the bare minimum.

### ISSUE THREAD

**Issue by NovemberOrWhatever** [KSP-RO/RP-1#2015]
On Discord, siimav said:
"OOOOOF. 
Let's say the DR SR rewards 20 rep. This would in turn raise my yearly subsidy by 1500 funds.
The SR itself costs 718+828; takes ~3 months to build with 102 engis. Each engi costs 42 funds per month which takes the total integration cost to 3 * 102 * 42 = 12.8k funds.
I'm better off not launching anything unless I REALLY have to."

**Comment by siimav** [comment]
Got rebalanced
