### ISSUE TITLE
Even a talented player going for reputation will struggle to get more than halfway to the max

### ISSUE THREAD

**Issue by NovemberOrWhatever** [KSP-RO/RP-1#2016]
I feel like that max should only exist if it's at least possible to get kinda close to it

**Comment by FioraAeterna** [comment]
FWIW, in my own run, which is "trying to play well but not outright speedrunning/cavemanning" by around 1963 onwards I've found myself capping the reputation max without too much trouble. So this might be an earlier game problem?
![image](https://github.com/KSP-RO/RP-1/assets/7761472/6168ab32-b53a-4b09-8f2e-e65f0c47e71a)

**Comment by siimav** [comment]
Probably fine now with rep rebalancing
