### ISSUE TITLE
Players feel like they have to chase the top of the rep curve - tooltip change to mitigate.

### ISSUE THREAD

**Issue by ppboyle** [KSP-RO/RP-1#2022]
Suggestion:  Change the rep tooltip to not mention that there is a maximum subsidy unless the player has exceeded it.  Only mention current subsidy, minimum, and subsidy gained per point normally.  Especially at the start of the game, the player is never going to feel like they can 'catch up' and they shouldn't.

**Comment by NathanKell** [comment]
Fixed
