### ISSUE TITLE
Math bug in repToSubsidy calculations

### ISSUE THREAD

**Issue by ppboyle** [KSP-RO/RP-1#2023]
In maintenanceHandler.cs

I believe the line details.maxRep= details.maxSubsidy/Settings.repToSubsidyConversion;

Instead should be details.maxRep = (details.maxSubsidy-details.minSubsidy)/Settings.repToSubsidyConversion;

Because currently the rep is interpolating between the range of min to max subsidy, not 0 to max subsidy.     Also we should set the tuning when this is changed back to 100 repToSubsidy, vs the current 150.

**Comment by ppboyle** [comment]
Actually since I'm working on tuning against the current game with the setting as-is, and so we have a buffer for a global tweak toward easier - if we do fix this, set repToSubsidy to 75 to keep the current behavior.

**Comment by NathanKell** [comment]
I thought we discussed and decided that you _should_ have an increasing rep floor as you progress? Because rep decay is slight enough that you'll keep building rep.
This change was due, IIRC, to changing required contracts to yield rep, vs. the original design of them giving no reward whatsoever.

**Comment by ppboyle** [comment]
Oh - I thought we decided to baseline our min subsidy to 0 rep, so that the player never fell into a place where adding some rep was meaningless to them unless they'd gone negative.

That's how it currently works, the only issue being that the repToSubsidyConversion tuning value is currently cut to 1/2 what it should mean because it's effects are calculated wrong.

**Comment by NathanKell** [comment]
Nope, I was just wrong about my memory here.
