### ISSUE TITLE
SPH upgrade fails if a recovered craft is "out of position"

### ISSUE THREAD

**Issue by silicon-ghost** [KSP-RO/RP-1#2024]
I have 1 aircraft (Sonic Cruiser) with a Derwent (no resources required) that has flown and been recovered.  I attempted to upgrade the SPH to support Draken with rocket engine.  [See this 7zip](https://drive.google.com/file/d/16xdOlu8mAnLlrY-ctsYxLrZ9uOHlwbKb/view?usp=sharing) for savegame, KSP.log and craft files
Steps to reproduce:
- Load from my save.
- in SPH, load "Draken-1a.craft"
- Click "Upgrade" on Integration window
- Click Renovate
[error message](https://cdn.discordapp.com/attachments/845457276641738782/1119424895500165210/image.png)

Workaround:
- edit existing recovered aircraft, move them back to center of hangar and save the edit
- Upgrade SPH will now work

Game details:
KSP 1.12.5
RP-1 v2.1.0 official release

**Comment by NathanKell** [comment]
IIRC this is an issue with KSP's detection of the dimensions of B9 Pwings, which is why a no-op edit fixes it.

**Comment by siimav** [comment]
Not B9 wings; it's caused by realchute instead.

**Comment by NathanKell** [comment]
Can we do something as part of the recovery process to clobber realchute sizing info? Force it to repack? Something like that?
