### ISSUE TITLE
Lunar orbiter and mapper contract doesn't work with in-avionics science

### ISSUE THREAD

**Issue by FioraAeterna** [KSP-RO/RP-1#2027]
![image](https://github.com/KSP-RO/RP-1/assets/7761472/bc023899-f0e4-47d9-b3be-02884db9be95)

Since this contract is required to complete the program, a lot of people are probably going to run into this one. If it's not fixable, at least a strong, bolded red warning should be placed in the contract.

**Comment by NathanKell** [comment]
Should be fixable by switching to the science collection parameter.

**Comment by siimav** [comment]
Fixed by #2083
