### ISSUE TITLE
Missing translations for some facilities

### ISSUE THREAD

**Issue by mateusviccari** [KSP-RO/RP-1#2028]
When hovering the mouse over the upgrade button, we only see a generic #autoLOC placeholder.
This happens only in the launchpad, VAB, SPH, and the runway.
Here's a screenshot.
![missing_translation](https://github.com/KSP-RO/RP-1/assets/8275175/edc68f28-cb3f-4122-9cc6-40be5fb34067)
Using the latest 2.1.0.0 version.

**Comment by NathanKell** [comment]
Could not reproduce: when I hovered over the button no change in tooltip was observed.
