### ISSUE TITLE
Sounding Rocket Payload in SM is kind of a trap

### ISSUE THREAD

**Issue by ppboyle** [KSP-RO/RP-1#2033]
I fell for this one despite knowing it last I played - players don't know where sounding payload goes.  You get a normal tank - won't go there because you haven't switched it to HP.  So you put down an SM and you can put it there - but its got a terrible dry mass ratio and costs more money to tool.

Suggestions:  
- SR payload can't go in a SM?

**Comment by marsh1832** [comment]
On the flip side it might confuse players wondering why their sat payloads don't fit in an HP tank. Sounding payload in an SM is suboptimal but isn't a career-ending choice to make

**Comment by FioraAeterna** [comment]
Perhaps a note in bold could be put about it in the first sounding rocket contract, to make sure players are aware of what's going on and why they should use HP tanks?
