### ISSUE TITLE
Orbital Science Probe missions missing confidence [patch included]

### ISSUE THREAD

**Issue by FioraAeterna** [KSP-RO/RP-1#2040]
![image](https://github.com/KSP-RO/RP-1/assets/7761472/f761b77b-ddfb-45dd-9d3f-e90e1e509cee)

I think I remember this mission having confidence when it was available under Early Inner Planet Probes, but under Venus Surface Exploration it's missing.

**Comment by FioraAeterna** [comment]
I suspect there is a bug going on where if an optional contract is normally under program X, but is also available under program Y, it doesn't give confidence.

**Comment by FioraAeterna** [comment]
Here's a patch that fixes the problem:

diff --git a/GameData/RP-1/Programs/Programs.cfg b/GameData/RP-1/Programs/Programs.cfg
index c690caeb..2a26592d 100644
--- a/GameData/RP-1/Programs/Programs.cfg
+++ b/GameData/RP-1/Programs/Programs.cfg
@@ -724,6 +724,7 @@ RP0_PROGRAM
 	OPTIONALS
 	{
 		probeVenus = true
+		VenusOrbitRepeatable = true
 	}
 }
 
It may be worth going over the other optional contracts to make sure none are missing in the same way.

**Comment by NathanKell** [comment]
Please PR the patch! Thanks :)

**Comment by FioraAeterna** [comment]
Fixed in https://github.com/KSP-RO/RP-1/pull/2049 .
