### ISSUE TITLE
Venus Orbit (and I assume Mars Orbit) do not require launching of a new vessel

### ISSUE THREAD

**Issue by westlakem** [KSP-RO/RP-1#2044]
When I launched my "Venus Flyby" vessel, I had the capability to put it in orbit instead, so I loaded it up with science instruments and put it in orbit. After completing the contract and establishing orbit, I went back and picked up the "Venus Orbit" mission.  Noticing it didn't require "launch a new vehicle", I was curious and loaded my existing craft orbiting Venus from the tracking center.  It immediately noticed the situation and started the count down until the contract completed.

![image](https://github.com/KSP-RO/RP-1/assets/4505074/c9e0de7e-8ada-4c19-a816-21b7273deb6e)
![image](https://github.com/KSP-RO/RP-1/assets/4505074/29bcfa5b-2b93-45ec-9bea-786d3b79ea7d)
![image](https://github.com/KSP-RO/RP-1/assets/4505074/e5370a55-0767-4ded-86d3-1deaa800a88c)

**Comment by FioraAeterna** [comment]
Allowing flyby and orbit to be completed in one flight seems like a good idea (especially given the time between launch windows for Mars and Venus). But it would probably be better to directly expose this to the player by making both missions immediately visible at the start, I think.

**Comment by westlakem** [comment]
Is there a way to combine the first orbit & flyby into one mission?  Maybe have "orbit" be an optional objective of fly-by, and then once the fly-by missions are complete immediately go into the repeatable orbit missions and sci orbiter / lander / whatever the next mission is?

**Comment by Tsits11** [comment]
I think that was the original idea , to be able to accomplish a flyby and(if possible) orbit using the same vessel and I think it’s fine the way it currently is

**Comment by Blothorn** [comment]
I agree that I don't see a problem with doing this in one launch, but I think the way these are structured makes it non-obvious that it is possible. Usually when two contracts like this can be completed in one launch they both require a new vessel, but can be accepted simultaneously--I didn't bother to look closely at the orbit contracts until I had completed a flyby and they unlocked, by which point it was much too late to make that first launch capable of launch.

I'd suggest removing the dependency of the orbital contracts on flybys--orbit can still allow reuse of a vessel to avoid tying up the contract slot while the spacecraft is in transit, but I think that unlocking them both from the start of the program would make the one-launch possibility more obvious.
