### ISSUE TITLE
[V2.2.0] New build lauch complex not visible

### ISSUE THREAD

**Issue by kretze** [KSP-RO/RP-1#2045]
I started a new game. built the first launch complex. but this is not displayed. not in operations and/or staff.

[imgur screenshot](https://imgur.com/a/CzrQWyL)

**Comment by NathanKell** [comment]
Did you check the construction tab? They don't build instantly.

**Comment by kretze** [comment]
I started a new game and wanted to restart it (because of the adaptation of the x-planes project and my experiences from the previous savegeame)
-> 1.1.1951 start of construction of the LC-01. Completion on February 10, 1951. I fast forwarded another day. the LC-01 is shown in the budget window, but there is nowhere to switch from the hangar to the LC-01.

**Comment by kretze** [comment]
I tested again with yesterday's savegame.
in the VAB I see the LC-01 and I can also add a rocket to build, but in the space center and in staff the buttons to switch between the LCs and the hanger are not shown.

---------
then i started a whole new game. everything works normally there.

I have the suspicion that it was connected with the first start after the update.
i compared yesterday's save with today's brand new testsave and i discovered a difference.

```
yesterday savegame
						LaunchPads
						{
							KCT_LaunchPad
							{
								level = 0
								id = 8eeeb1e9-8ce5-49e5-b0cf-b53c796fa0d9
								fractionalLevel = -0.474999994
								isOperational = True
								name = LC-01-A
								launchSiteName = LaunchPad
								DestructionState
								{
								}
							}
						}

``` 

```
today savegame
						LaunchPads
						{
							KCT_LaunchPad
							{
								level = 0
								id = 905f7ea8-d880-40c8-a555-b6edc78c6431
								fractionalLevel = -0.474999994
								isOperational = True
								name = Launch Complex 1-A
								launchSiteName = LaunchPad
								DestructionState
								{
									SpaceCenter/LaunchPad/Facility/Flag
									{
										intact = True
									}
								}
							}
						}

``` 

the DestructionState was not set yesterday after building LC-01. could that have been the cause?

**Comment by NathanKell** [comment]
No idea, but no one else has reported this issue, so I'd chalk it up to gremlins. Please make a new issue with repro steps if you (or anyone else) encounters it again.
