### ISSUE TITLE
Venus gazette appears incorrectly

### ISSUE THREAD

**Issue by FioraAeterna** [KSP-RO/RP-1#2051]
This appeared when I did my first atmospheric probe / lander -- not when I did my first flyby or orbit. The text suggests it's meant to appear on flyby or orbit.

![image](https://github.com/KSP-RO/RP-1/assets/7761472/153cf7a9-16ad-43d8-8b76-db056a91cc1e)

**Comment by NovemberOrWhatever** [comment]
It was set to probeVenus instead of flybyVenus. Fixed now
