### ISSUE TITLE
Second landing contract is missing confidence

### ISSUE THREAD

**Issue by FioraAeterna** [KSP-RO/RP-1#2052]
![image](https://github.com/KSP-RO/RP-1/assets/7761472/7e926b74-4fe9-42e3-af5b-f823f6fbdfcb)

Since the rule of P&LC seems to be that "optional contracts give confidence", this second venus landing (optional) should definitely give confidence even though the first (required by the program) does not. This will probably require creating a VenusLandingOptional contract or something like that...

**Comment by siimav** [comment]
Looks like `landingVenusRepeatable` contract exists now
