### ISSUE TITLE
Staffing window is bugged

### ISSUE THREAD

**Issue by Test-Account-KSP** [KSP-RO/RP-1#2053]
There are many issues when entering mission control building with "Staffing" window open:
- Missions list is not repopulated (if it was empty, it stays empty, etc.)
- If a mission is accepted in this state, it does not stay accepted after exiting the building
- If the staffing window is closed while in mission control, it will open itself again after exiting the building

**Comment by NathanKell** [comment]
Gonna need more details on this. I can reproduce the third one, but not the other two.

**Comment by Test-Account-KSP** [comment]
Strange, just tried #2 and it worked as it should.

**Comment by Test-Account-KSP** [comment]
Can't reproduce either, no issue now.
