### ISSUE TITLE
Hire button in the Staffing window is unsafe

### ISSUE THREAD

**Issue by Test-Account-KSP** [KSP-RO/RP-1#2054]
Hire button in the staffing window reacts to the Alt key, which sometimes gets stuck after alt-tabbing. If this is not noticed, the button will spend all the money to hire huge a number of staff. This cannot be undone and simply ruins the game.

Alt-click should be either disabled or a confirmation dialog added to it.

**Comment by NathanKell** [comment]
The window shows exactly how many staff you'll be hiring (on the button) before you press the butotn.

**Comment by Test-Account-KSP** [comment]
Surely it does. Mistakes still happen. 
With this kind of logic though, it will be the last issue I will ever leave here, as it's clear that all of them will be rejected.

**Comment by NathanKell** [comment]
Given that I am currently trying to reproduce your Staffing Window Bugs issue, that seems a bit dramatic, but sure.

**Comment by Test-Account-KSP** [comment]
The staffing window bugs issue was submitted before this conversation...
Sorry, my previous message it was indeed dramatic and not right.

**Comment by NathanKell** [comment]
No worries! There's just, as you might imagine, an awful lot of bugs and not an awful lot of dev to go around. :]
