### ISSUE TITLE
Add Hire 10 button in the Staffing window

### ISSUE THREAD

**Issue by Test-Account-KSP** [KSP-RO/RP-1#2055]
The Hire button in the staffing window hires 1 person, which is never enough. I usually need to use Shift-click to hire 10 people at once. 

There should be a button to hire 10 people with one click without having to press shift.

**Comment by batuhantasli** [comment]
You can also use ctrl and alt keys to hire more people.

**Comment by Test-Account-KSP** [comment]
Ctrl to hire 100, alt to hire as much as I can. Not related to hiring 10, which is what I usually need.
