### ISSUE TITLE
Improvement of the Operations tab

### ISSUE THREAD

**Issue by Test-Account-KSP** [KSP-RO/RP-1#2057]
The tab name "Operations" is unclear. The term is not used anywhere else. 
It should be called "Launch Complexes", which is longer but makes sense.

The tab "Operations" also shows launch complexes one by one. There is no view showing the list of all launch complexes, what they are doing at the moment, if they are idle or rushing. Such a view should be added.

**Comment by NathanKell** [comment]
Adding a launch complexes overview is nontrivial and I'd like to save that for a more comprehensive UI overhaul rather than doing wasted imgui work. Fixed the other part of the issue however! :)
