### ISSUE TITLE
Launch Complex Specifics make testing engines (with Modular Launch Pad's Test Stands) difficult

### ISSUE THREAD

**Issue by smunstu** [KSP-RO/RP-1#2059]
The max number of engineers available to be assigned to a complex seems to be based on tonnage of the launch complex.

However, anything attached to a test clamp (from modular launch pads) has no weight, and therefore cannot be used to easily test complex engines due to the long assembly times. At most, you can have 10 engineers assigned to such a complex.

**Comment by siimav** [comment]
You aren't supposed to *test* engines in the first place. The 0 data units on engines already reflects them being extensively run on test stands.
