### ISSUE TITLE
Hangar Softlock

### ISSUE THREAD

**Issue by MeatyBoiYT** [KSP-RO/RP-1#2066]
The switch to hangar button is broken, I cannot start the process of building anything in the hangar, I am effectively soft locked from doing the X-Plane contracts.
![image](https://github.com/KSP-RO/RP-1/assets/70345189/2a850b44-1512-4da3-baf2-761db48c5c0e)

**Comment by NathanKell** [comment]
Doesn't seem to be reoccuring. If you (or anyone else) suffers this, please repost with (a) logs, and (b) repro steps.
