### ISSUE TITLE
R&D building upgrades are useless and should be removed

### ISSUE THREAD

**Issue by NovemberOrWhatever** [KSP-RO/RP-1#2075]
Mechanically, they are basically identical to just hiring more researchers, except if you forget to do it ahead of time it can mess with you. This doesn't seem like a system that needs to exist.

**Comment by Test-Account-KSP** [comment]
Maybe these upgrades should instead affect research efficiency, like they did in legacy?

**Comment by NovemberOrWhatever** [comment]
Except that mechanic is already implemented through electronics research blue sky nodes

**Comment by Test-Account-KSP** [comment]
Which makes it gated by a specific year, rather than the player's progress

**Comment by NovemberOrWhatever** [comment]
I just don't see why we should implement paying money for faster research through methods other than hiring more researchers

**Comment by FioraAeterna** [comment]
The upgrades are also a huge money sink, to the point where funding them is a significant burden over the course of the game. Removing the upgrades will probably make the game significantly easier.

**Comment by NovemberOrWhatever** [comment]
If we don't want to mess with game balance, we can just make researchers slightly more expensive or subsidy slightly less. I just don't see how the current system for R&D upgrades is in any way interesting, mechanically. (I'd PR this change myself but I don't know how to do the cosmetic upgrades automatically)

**Comment by NathanKell** [comment]
It's a fund sink, but it's: a fund sink that you _don't have to pay_ at the start of the game, where increasing researcher salaries you would. It's also not something you can scale up instantly, like hiring a hundred researchers (or firing them!).

**Comment by marsh1832** [comment]
One thing you can think of it as, is a literal building. You only have so much room for your researchers, and above a certain point you need to build a new/bigger facility for them to work in.

**Comment by byt3c** [comment]
We could make it a bit faster though, some build times are really long and feels like an obstacle rather than progress. You basically need to start building it for the sake of its construction length rather than when you actually thinking of increasing capacity.
