### ISSUE TITLE
Career Log Export to file Column Headings Incorrect

### ISSUE THREAD

**Issue by dcwhitworth** [KSP-RO/RP-1#2078]
It appears that the VAB column contains the total number of engineers instead of it being split between VAB and SPH. This results in all the other data columns being shifted one to the left relative to their headings. I guess the fix would probably be to merge the VAB and SPH columns as 'Engineers' And change the RnD to Researchers.

Also the Contract advances, Contract rewards, Contract penalties and Other funds earned columns seem to be redundant

**Comment by NathanKell** [comment]
Fixed

**Comment by NathanKell** [comment]
Well, you're right about the redundant columns too tho. @siimav should we just nuke that data and those columns?
