### ISSUE TITLE
Per NK on stream, move the medium radial sep motor to an earlier tech node

### ISSUE THREAD

**Issue by ppboyle** [KSP-RO/RP-1#2079]
Currently its 4 tech nodes down the solids line.  Since its not that performant - just a bigger sep motor - it should be moved up a couple of nodes.

**Comment by pap1723** [comment]
Fixed with https://github.com/KSP-RO/RP-1/commit/c39c2969673997b9cbb2d5c4f36c5d64dc8283b2
