### ISSUE TITLE
Typo in administration building

### ISSUE THREAD

**Issue by dandoesgithub** [KSP-RO/RP-1#2086]
There's a typo in "Crew Safety", it should say "-10% to integration speed of cockpits", instead it says "-10% to integration speed of of cockpits"

![image](https://github.com/KSP-RO/RP-1/assets/54538634/d7d403ac-dbe0-4a08-b7b4-6f9c9c9eafd9)

**Comment by siimav** [comment]
Fixed in 21e5029da5a36f3b34dd44bc4582a64c28bb302f
