### ISSUE TITLE
It should not be possible to hire leader "Research MatSci first"

### ISSUE THREAD

**Issue by Test-Account-KSP** [KSP-RO/RP-1#2093]
As the title says, this leader can be appointed, which makes no sense.

![image](https://github.com/KSP-RO/RP-1/assets/110846612/5ba07d3b-7df2-4179-ad1b-c1fb27cb9fc8)

![image](https://github.com/KSP-RO/RP-1/assets/110846612/1bddb6ec-0058-4c38-854d-81aba965b4e4)

**Comment by NathanKell** [comment]
Finally thought of a reasonably easy way to fix this, so I've fixed it. It's just honestly not been a priority since appointing them is harmless.
