### ISSUE TITLE
Critical issue: the cost of administration building upgrade rises mid-construction!

### ISSUE THREAD

**Issue by Test-Account-KSP** [KSP-RO/RP-1#2094]
The second upgrade of admin building costs 140000, and it started upgrading at 140000, but then changed to something much higher.
This happens when the game is saved and loaded via the main menu.  Before saving the upgrade cost is 140000, after loading the game from main menu it's 400000.

![screenshot4](https://github.com/KSP-RO/RP-1/assets/110846612/9374fa05-4465-44f1-97eb-0bc15565d436)

**Comment by NathanKell** [comment]
KSPCF bug (still my fault though :D ) -- fixed in KSPCF 1.29.2.
