### ISSUE TITLE
RP-0 KCT Didn't work in Sandbox

### ISSUE THREAD

**Issue by Zoeille** [KSP-RO/RP-1#2095]
Hi, After migrating to Legacy sandbox (we can't use RP-1 yet) I saw that when you are in sandbox, KCT don't load its menu, but load its menu in career (I created a brand new save game in the 2 mode to be sure it's not a save issue)

No errors in the logs and in the console when I click on the button. Left-click open the config menu, Right-click do nothing in sandbox

**Comment by siimav** [comment]
Right click on the KCT button and re-enable KCT
