### ISSUE TITLE
No MMH + MON1 RCS engine option

### ISSUE THREAD

**Issue by byt3c** [KSP-RO/RP-1#2097]
there is no MMH+MON1 RCS option despite Apollo D2 having it as RCS. 
![obraz](https://github.com/KSP-RO/RP-1/assets/38114978/68f8b451-f602-4e4c-8d4f-a9804af5ed46)

**Comment by NathanKell** [comment]
You're correct, it's not a Generic config option. Neither is, say, LF2 + AK27. There are only some Generic RCS configs.

**Comment by byt3c** [comment]
Maybe we can change all MON1, MON3, MON5, MON10 to just MMH+MON RCS engine since they have basically the same stats and it would solve all complexities and issues with current designs ? It should simplify the selection as well :)
