### ISSUE TITLE
First Solar Powered Satellite contract incorrectly completes

### ISSUE THREAD

**Issue by Amselfass** [KSP-RO/RP-1#2099]
**Environment:** RP1 v2.4.1 on KSP 1.12.3.3173

**Steps to reproduce:**
1. Download and open [this save](https://github.com/KSP-RO/RP-1/files/12002809/FSPS.Bugreport.zip).
2. Observe that the First Solar Powered Satellite contract is active and has all steps completed except for _"Resource: ElectricCharge: At least 100 units"_. This is due to a previous craft _Hermes 2_ (now marked as debris, but can still be accessed from the tracking station if required), which completed all other parameters, but could not stay above 100 EC.
3. Launch _Hermes 3_ from LC-3-A.

**Observed behaviour:** On vessel load, the contract will complete.

**Expected behaviour:** The contract should not complete, its parameters should instead be reset for the new vessel.

**Comment by ppboyle** [comment]
Fix pushed to master.
