### ISSUE TITLE
NullReference in KSP.log, apparently from get_ResearchSalaryPerDay

### ISSUE THREAD

**Issue by Test-Account-KSP** [KSP-RO/RP-1#2101]
[EXC 23:17:22.273] NullReferenceException: Object reference not set to an instance of an object
	RP0.MaintenanceHandler.get_ResearchSalaryPerDay () (at <3cc560f73d17444795c384e0d85660f7>:0)
	RP0.MaintenanceGUI.RenderSummaryTab () (at <3cc560f73d17444795c384e0d85660f7>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:LogException(Exception)
	RP0.MaintenanceGUI:RenderSummaryTab()
	RP0.TopWindow:DrawWindow(Int32)
	UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)
[EXC 23:17:22.274] NullReferenceException: Object reference not set to an instance of an object
	RP0.MaintenanceHandler.get_ResearchSalaryPerDay () (at <3cc560f73d17444795c384e0d85660f7>:0)
	RP0.MaintenanceGUI.RenderSummaryTab () (at <3cc560f73d17444795c384e0d85660f7>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:LogException(Exception)
	RP0.MaintenanceGUI:RenderSummaryTab()
	RP0.TopWindow:DrawWindow(Int32)
	UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)

[KSP_log.zip](https://github.com/KSP-RO/RP-1/files/12021568/KSP_log.zip)

**Comment by NathanKell** [comment]
What's the situation in which this occurs? Does it reproduce reliably?

**Comment by Test-Account-KSP** [comment]
Tbh I don't know, I just opened ksp.log to check if there are null reference exceptions and found it.
