### ISSUE TITLE
Suggestion on progression and Downgrading 

### ISSUE THREAD

**Issue by Tsits11** [KSP-RO/RP-1#2105]
So I’ve reached 1975 , finished moon landing and upgraded my facilities to lvl 3+++. However despite having multiple active programs and firing excess engineers and researchers my total income is stil negative.

shouldn’t there be an option to downgrade say RnD building not that it’s no longer needed at this high lvl ?

**Comment by NathanKell** [comment]
There is, the same that's in stock KSP. IIRC it's either alt-click or ctrl-click on the facility to give the option to downgrade rather than upgrade.

**Comment by Tsits11** [comment]
NathanKell listen right now the only option is to demolish and then rebuild at the previous level which costs a lot and takes time, you know what I’m saying ?

> 
![image](https://github.com/KSP-RO/RP-1/assets/113089271/c37edf12-51b5-419d-b15c-32e8f62d570a)

**Comment by NathanKell** [comment]
Does this not work?
https://forum.kerbalspaceprogram.com/topic/98822-how-do-you-downgrade-buildings/?do=findComment&comment=1701150

**Comment by Tsits11** [comment]
As Is clear from the picture I posted above, the problem is that, yes it IS possible to downgrade although it takes time to “reconstruct” and it costs 333K
