### ISSUE TITLE
Science 'career' mode completely broken

### ISSUE THREAD

**Issue by ArtOfStuttering** [KSP-RO/RP-1#2117]
Recently wanted to dive into KSP again but didn't want to manage funds, rep, etc. so decided to give Science mode a go. Turns out, that's utterly broken.

First of, when starting a new campaign it doesn't auto-unlock the node "Starting Parts", locks it behind a 999 science.
Secondly, when going through the intro/config menu where it says to apply the 50 staff, it throws a ton of errors in the console: "Exception: NullReferenceException: Object reference not set to an instance of an object." Taking a wild guess that this is because there's no LC.
Third: When I create a 'rocket' out of the available parts and then press create a LC it once again errors out.
Fourth: It tries to draw the Staffing menu as below. No way to hide that after.
![image](https://github.com/KSP-RO/RP-1/assets/6819868/e56e40a9-7ff1-4487-8a63-753d381f3c6a)

**Comment by siimav** [comment]
We don't support Science Mode at all so fixing those issues would be rather low in the list of priorities. :pr_welcome:

**Comment by NathanKell** [comment]
As closely tied as RP-1 is to funding and reputation, it's not feasible to support Science Mode. If you want to play in Science Mode More Or Less then I suggest just cheating a bunch of money in? That's what people usually do when they want to play an ersatz Science Mode career.

We should probably remove the option for science mode, however.
