### ISSUE TITLE
Impossible to stay cash-positive after crewed lunar landings program runs out + small comment on research speed balance

### ISSUE THREAD

**Issue by SAOBunk** [KSP-RO/RP-1#2129]
I recently completed, on normal difficulty, the crewed lunar landing program.
Before RP-1 v2.0 you would effectively enter a sandbox where money was of little concern, as there were plenty of short contracts you could keep completing for cash injections. However, now that funding only comes from programs, that situation has changed dramatically. 
Once you complete this program, your income drops dramatically, and there are no programs that could hope to replace the funding you lose before you go bankrupt. The only program which has a hope of replacing that funding is Plutonian Landings, but that isn't available before you complete the much less lucrative Outer Planet Flyby program, which is unlikely to be successfully completed before you go broke from expenses.

It seems undesirable to me that you would have to fire large amounts of your research staff after the lunar program concludes, even though that mirrors what happened in reality.

Before P&LC you likely would have moved on to large space stations and more permanent lunar habitation, but those programs are not implemented yet.
Perhaps as a temporary solution a permanent subsidy could be introduced after you complete the lunar program, which pays out 3 million funds per year. With this subsidy, you do not have to dramatically involuntarily reduce the size of your space program.
Or, if you want players to have to put in more effort to continue receiving funding for their programs, introduce a repeatable lunar surface tourism contract, which pays out large sums of money when completed, though I realize such a contract goes against the philosophy of P&LC.

This is a screenshot of my budget screen, with the Mars Surface Exploration, Venus Surface Exploration, and Small Bodies Flyby programs active. You can see the gigantic deficit. I have 4447 engineers and 5500 researchers.
![image](https://github.com/KSP-RO/RP-1/assets/21249575/b7610b35-7417-4e97-8afa-53f8db249c97)

Aside from post-lunar cash balance, I have some thoughts on research balance.
I think that whilst the research balance is nearly perfect, keeping good pace with most historical dates for firsts, it seems to be impossible to recreate, using accurate parts, the Apollo 11 mission before the real-life date. I was upgrading R&D and staffing it maximally for nearly the entire duration of my space program, whilst making sure to always prioritize the electronics research nodes for the research speed boost. Despite this, I did not unlock all the parts required for a Saturn V mission until after 1969, by which point I had already completed all contracts required by the program. 
I completed the first crewed lunar landing in 1968 by using a smaller 1500t design based on the D-2 parts and a custom hydrolox lunar lander, so it is still possible to slightly beat the historical timeline by using non-historical designs. Before P&LC it was no problem at all to meet the historical date for the lunar landings using historically accurate designs, so maybe that part of the balance needs some more attention.

**Comment by Tsits11** [comment]
I actually have the same problem and recently opened a new issue thread regarding the possibility of downgrading the RnD building. Unfortunately my issue was easily dismissed. 

however the issue persists, once you complete the lunar landing it’s impossible to go cash-positive. It’s also absurd that a mission to Jupiter and its moons give you around 4m in total (the mission can take you in excess of 3 years to complete. 

After lunar landing the cost just for facilities and researchers maintenance is roughly 3m per year !!!

**Comment by NovemberOrWhatever** [comment]
Yeah, this will be fixed when we have more programs. Not much you can do now but cheat in funds, unfortunately, unless you want to write contracts for more programs. It's a temporary issue, but for now you can just consider the game complete when you finish crewed lunar.

**Comment by Tsits11** [comment]
Are you at least considering of bumping up programs like Jupiter/Saturn exploration to pay out more funds ?

**Comment by Test-Account-KSP** [comment]
That would be free money

**Comment by NathanKell** [comment]
As November says, it's reliant on there being more programs, so this isn't really an issue as such, just...yeah, more content would be good, wouldn't it? :D
