### ISSUE TITLE
Sounding and satellite payload rounding errors

### ISSUE THREAD

**Issue by Test-Account-KSP** [KSP-RO/RP-1#2133]
Sounding rocket contracts, 4500+ km downrange contracts and many satellite contracts ask for a fixed amount of sounding/comsat/navsat/weather sat payload.  However, there is rounding in the game that can result in 499.99 shown as 500 and the contract not completing, even though the player was sure that the rocket has enough payload.

The proposal is make all these contracts check for (contract amount - 0.1) payload.  So for example, a sounding rocket contract would ask for 75 So, but in fact check that the rocket has 74.9 So.

**Comment by Test-Account-KSP** [comment]
Now that I look into a downrange contract, I see that something similar already exists:
minQuantity = @/missionPayload - 0.01
But there are still complaints and screenshots of 500 sounding payload in the VAB but no mission completion.
I suppose 0.01 is not enough and should be changed to 0.1?

![image](https://github.com/KSP-RO/RP-1/assets/110846612/2989cb5b-b3af-4320-81db-16e7b2fe33ce)

**Comment by Teykn** [comment]
I feel like a note or popup when you first accept a contract with payload which lets you know to rely more on the tank UI’s number rather than the stock GUI’s readout would be more useful

**Comment by Test-Account-KSP** [comment]
Why complicate things over 0.1 payload, it's not worth it
