### ISSUE TITLE
the snap and symmetry buttons no longer work with X and C

### ISSUE THREAD

**Issue by ChoccoAerospace** [KSP-RO/RP-1#2141]
For the symmetry, i now have to press the button manually to increase. for the snap, it is now just 15 degrees and none, i can't get any other snap.

**Comment by Capkirk123** [comment]
Please make sure you update Editor Extensions Redux to the latest version, and then try again

**Comment by ChoccoAerospace** [comment]
it was already in the latest version

**Comment by Capkirk123** [comment]
And what version is that? Also, try setting the keybinds in the KSP settings menu.

**Comment by ChoccoAerospace** [comment]
CKAN says i downloaded 3.4.3.5 and the latest version is 3.4.3.5

**Comment by Capkirk123** [comment]
That is not the latest version of Editor Extensions Redux. Try restarting and updating CKAN.

**Comment by ChoccoAerospace** [comment]
i updated CKAN and it still was the latest version. Although, i did check my keybindings, they had changed for some reason

**Comment by NathanKell** [comment]
Sounds like you've been bitten by the "CKAN won't show me new versions of mods" bug. Please post an issue on the CKAN repo about this. https://github.com/KSP-CKAN/CKAN/
