### ISSUE TITLE
Soviet probes parts do not show up

### ISSUE THREAD

**Issue by Tsits11** [KSP-RO/RP-1#2146]
I have an issue where I have soviet probes and rockets mods installed, fully updated via ckan, everything worked great up until a few weeks ago and now I suddenly noticed that the soviet probes won’t show up in my tech tree… in the setting I’m already playing in speculative parts so that’s not an issue. Soviet rocket parts do show up however as do us probes (voyager Galileo etc)

**Comment by Capkirk123** [comment]
This is because they are not configured for uses in RP-1, and is expected behavior until someone does configure them.
