### ISSUE TITLE
Incorrect unlock credit display for the "Year" period

### ISSUE THREAD

**Issue by Test-Account-KSP** [KSP-RO/RP-1#2150]
Unlock credit display in the budget window in new RP1 version isn't very correct. It seems to be correct for "day" and "month" periods, but not for "year", where it apparently shows unlock credit gain until the end of the current calendar year (?).  

![image](https://github.com/KSP-RO/RP-1/assets/110846612/98160e02-5d77-49fd-88c0-7b8d8ee38b06)![image](https://github.com/KSP-RO/RP-1/assets/110846612/a31a30d7-9f0d-47fe-9c20-1389e0123c17)

**Comment by NathanKell** [comment]
Per discord, this sounds like you ran out of to-be-researched nodes after 169 days of research.
