### ISSUE TITLE
Uncrewed Lunar Surface Exploration program, bugged mission order

### ISSUE THREAD

**Issue by SierraHotel84** [KSP-RO/RP-1#2156]
The Uncrewed Lunar Surface Exploration program requires:
-Complete First Lunar Landing (Uncrewed)
-Complete First Lunar Orbiter & Mapper (Uncrewed)
-Complete First Far Side Lunar Landing (Uncrewed)

Once the First Lunar Landing contract is completed, Lunar Landing (Uncrewed) contracts become available, with 1 required and 2 optional. 
The required First Far Side Lunar Landing contract is gated behind completing one of the lunar landing contracts, instead of the original First Lunar Landing contract.

**Comment by Tsits11** [comment]
Can confirm , I had the same issue as well
