### ISSUE TITLE
Editing craft while procedural fairing is toggled open makes vehicle unbuildable

### ISSUE THREAD

**Issue by ehbar** [KSP-RO/RP-1#2162]
If you have a craft with procedural fairings, and they are toggled open, editing the craft will update the vehicle size to include the expanded fairings, possibly (greatly) exceeding the width and length allowed by your launch complex.

(The workaround is to close the fairings and again edit the craft, snap the nose off and on or something.)

Not sure if this is a PF or RP-1 bug, let me know if I should refile it over there.

<img width="640" alt="working" src="https://github.com/KSP-RO/RP-1/assets/11069565/64538add-2177-4e62-90c7-da29b391872b">

<img width="640" alt="busted" src="https://github.com/KSP-RO/RP-1/assets/11069565/474a4a1b-0453-4de5-9c23-42810b8af06b">

**Comment by NathanKell** [comment]
This is indeed a PF issue, namely https://github.com/KSP-RO/ProceduralFairings/issues/45
Cheers!
