### ISSUE TITLE
VAB Purchase buttons are busted

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/RP-1#2164]
from https://discord.com/channels/319857228905447436/1115321536807718992/1137853032474878002

Purchase buttons in the VAB part catalog seem under the impression that they have infinite unlock credits to spend. Tooltip says "cost after credit" is 0 even when there's 0 credits left; button is enabled even if there's not enough money to buy the upgrade; clicking it sends the finds balance into the red.

**Comment by NathanKell** [comment]
Fixed in https://github.com/KSP-RO/RP-1/commit/b5be409646d379bb1d7c61dfb7b950ebf18f00c8
