### ISSUE TITLE
Saving invalid vessel edits costs funds

### ISSUE THREAD

**Issue by djmyhill** [KSP-RO/RP-1#2173]
When saving edits to a vessel in KCT and the edits dont pass editor checks, the entire cost of the vessel is taken from the player's funds (even if the player has negative funds). To replicate it:

1. Start building a vessel in an LC
2. Edit it in a way that the LC does not allow

**Comment by Elouda** [comment]
Can confirm this, it also happens if for example the edit has parts that need unlocking, and you hit the 'acknowledge' button instead of the 'unlock and purchase' button when it pops up.
