### ISSUE TITLE
Adding procedural service module while editing already built vessel resets progress to zero 

### ISSUE THREAD

**Issue by olegst90** [KSP-RO/RP-1#2177]
Not sure if it's a bug or it's intended so, but when I add Procedural service module to already built vessel edited percentage resets to zero. The same happens when adding a new procedural avionics part

**Comment by NathanKell** [comment]
Sounds intended--you've changed the buildtime of the vessel enough that KCT considers the change too large to preserve progress. This is especially common when the progress on the vessel is low already.
