### ISSUE TITLE
Cost petals as like 0.75x decouplable fairing sides

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-1#2187]
Definitely shouldn't be costed as stringers. Probably needs RP-1 support for tooling.

**Comment by NathanKell** [comment]
This is done on PF side already (yay thanks @ryanc55 ) I just need to poke at tooling some.

**Comment by ryanc55** [comment]
Another option would be to implement an open-once vs. re-closable choice.   Re-closeable could then be tooled as a regular fairing with even higher cost.   Open-once could get separate tooling, but they are supposed to be the poor-man's fairing with much simpler actuating hardware and timing vs. decouplable.  Historically just one explosive bolt and a spring.

**Comment by NathanKell** [comment]
That's a neat idea! For now I'll do the tooling thing just so we're good, and we can examine whether adding more options to the petal mode makes sense.
