### ISSUE TITLE
Can't simulate aircraft without a hired astronaut

### ISSUE THREAD

**Issue by Blothorn** [KSP-RO/RP-1#2188]
Now that there aren't any astronauts at the start, you need to hire one in order to simulate anything requiring a pilot. It's easy enough to save/hire/test/load, but it would be really nice not to have to if practical.

**Comment by NathanKell** [comment]
You should be able to simulate with applicants. @siimav made that change here. https://github.com/KSP-RO/RP-1/commit/b2d8ad4ec7a5985e19fbdaac53368fe1d5a1beda
