### ISSUE TITLE
Possible to start training with no one in it

### ISSUE THREAD

**Issue by Capkirk123** [KSP-RO/RP-1#2189]
Just like it says on the tin. It is possible to start mission/proficiency training with no astronauts in it, further compounded by the UI, which requires you to specifically select which astronauts you want to train from a list. I have witnessed at least two youtubers make this mistake, and have made it myself.

It should probably not be possible to start training if no astronauts are selected, or at least display a warning.

**Comment by NathanKell** [comment]
Amazing. I specifically fixed this bug recently except apparently it doesn't prevent you from clicking start, it only _tells_ you you haven't met the minimum requirements for the course.
