### ISSUE TITLE
Stringers fairings are not detected anymore in 2.9.0.1

### ISSUE THREAD

**Issue by Karhgath** [KSP-RO/RP-1#2192]
Seems the refactoring for the hinged fairings around the isDecoupled cannot properly detect if the fairings are staged or not anymore and thus cannot detect stringers which now forces costly tooling on what was previously stringers.

Before, the value was fetched on every OnStateUpdated but now with EnsureFields(), it is fetched only once - not sure if this is the issue or not.

https://github.com/KSP-RO/RP-1/commit/bfbf33ffb5b36118d3bcf1ff773cb706c868a899

**Comment by ryanc55** [comment]
I'm unable to replicate this issue.   With decoupler disabled, petal and non-petal fairings are showing as stringers in the tooling window.   I've tried new and very old craft files.   Do you have a craft file that shows the issue?

**Comment by ryanc55** [comment]
In 2.9.0.1, Non-decouple hinged fairings should have their own tooling and should show as "HingedFairing" in the tooling interface.   They are .75x the tooling cost of payload fairings.   If they also decouple they will tool as PayloadFairings.  If you're seeing something different, can you attach an affected craft file to this issue?

**Comment by Karhgath** [comment]
Were you able to replicate? In any case, here's a craft with boattail stringers normally. I also tried new craft and different adapter types with the same results. Only thing I have not tried is a new save on 2.9.1.

I am also not specifically using anything hinged (is that gated by tech?)

[[DR0-900 Film+Bio] Thunder-Al-101.zip](https://github.com/KSP-RO/RP-1/files/12411214/DR0-900.Film%2BBio.Thunder-Al-101.zip)

**Comment by Karhgath** [comment]
I am reupdating to 2.9.1 and will try a new save, had to rollback to not have to pay 6k of tooling on my current career.

**Comment by ryanc55** [comment]
Those show as stringer for me.  A new save shouldn't matter.   Are you on the latest version of Procedural Fairings?

**Comment by NathanKell** [comment]
Are you sure your PF is up to date?

**Comment by Karhgath** [comment]
I was on the last express install I did and only updated RP-1 on ckan, but now I see a few other updates available. 

I am booting with everything updated, I have a feeling that was it :(

I did not anticipate a minor patch to have hard dependency like that, so did not even think to check, my bad.

**Comment by ryanc55** [comment]
I'd say it's a bug that CKAN doesn't enforce the version dependency.   If this becomes an issue for more folks we can look at putting in regression compatibility to the RP-1 changes.  For now please report back if that fixes the issue so we can close this.

**Comment by NathanKell** [comment]
Very often our updates are interrelated, especially RP-1 and RO. It's important to upgrade, but it's also important to grab *everything*.

That said I didn't anticipate this breaking on older PFs, so apologies.

**Comment by Karhgath** [comment]
All good, just tested and that was the issue.

My filter in ckan was also set to "is:upgradeable rp-1" so that was part of it. Will make sure to keep everything updated at the same time. Thanks!

**Comment by ryanc55** [comment]
Thanks!  Closing.

**Comment by ryanc55** [comment]
Thanks! Closing.
