### ISSUE TITLE
Firing Milton Rosen strategically leads to more funding on ongoing programs, especially with funding peaks

### ISSUE THREAD

**Issue by Karhgath** [KSP-RO/RP-1#2207]
It seems the calculation when you hire/fire Milton does not work properly during a program lifetime, especially for programs with peak funding.

For example, firing Milton after the Light Sat peak puts you back to before the peak.

![image](https://github.com/KSP-RO/RP-1/assets/440648/ec1f3b5e-c634-45f1-96a9-562e91f4255d)

And the recalculated funds clearly shows you are getting much more funding out of the program. (it thinks you got way less money than you actually did)

Same for evenly distributed programs, although less severe.

![image](https://github.com/KSP-RO/RP-1/assets/440648/1d84260f-90c0-4040-97aa-55f33b4e1d23)

Hiring or Firing Milton should probably contract/expand the curve at the current position you are in the program timeline, not always at point 0 (start of the program).

**Comment by NathanKell** [comment]
This is a surprisingly large refactor. I'm aware of the bug but punted on solving it "properly" prior to RP-1 v2.0's release. (It would take a bunch of work--tons of the program code makes assumptions around comparing current UT to program accept UT and excepting that to yield a never-changing fraction vis-a-vis program duration).
