### ISSUE TITLE
Some contractors do not work

### ISSUE THREAD

**Issue by Codelet** [KSP-RO/RP-1#2209]
ОКБ-1 Korolev (as secondary contractor) does not increase the research speed of command modules
ОКБ-456 Glushko (as main contractor) has no impact on integration speed of R-7 family rocket
ОКБ-456 Glushko (as secondary contractor) does not increase the staged engines research speed

**Comment by NathanKell** [comment]
Could not repro OKB-456 main contractor bug--it's slight but it's there. Recall you have to start integrating a vessel _after_ appointing the leader for parts-based integration rate modifiers to take effect (or edit an already-integrating vessel).

**Comment by Codelet** [comment]
@NathanKell ok, if I edit the craft I can see the difference, but if I assign contractor and then click duplicate on the craft which was started before - the contractor bonus is not applied and I need to edit it and just save with no changes to get the bonus. same goes if I add the craft to Plans before contractor activation, craft created from plans still has no bonus. Feels a bit buggy :) Anyway thanks for the edit vessel hint.
