### ISSUE TITLE
E-1 Engine Upgrade configs incorrect 

### ISSUE THREAD

**Issue by SerinaLikesBugs** [KSP-RO/RP-1#2210]
![image](https://github.com/KSP-RO/RP-1/assets/97364742/b1309333-292b-4d22-beb7-88a9829aed9e)

![image](https://github.com/KSP-RO/RP-1/assets/97364742/3fdda85b-56e1-444e-90e8-1d5f6b9dbf70)

**Comment by SerinaLikesBugs** [comment]
I've not yet unlocked the supposed relevant nodes to the E-1 Engine upgrades but I'm able to use them regardless.

**Comment by NathanKell** [comment]
@Capkirk123 did these upgrades not get added to partsbrowser?

**Comment by NathanKell** [comment]
Fixed in https://github.com/KSP-RO/RP-1/commit/3be026630e2843087a0f5a0aebf247deec4d5dc5
