### ISSUE TITLE
Show tech nodes' category in RnD

### ISSUE THREAD

**Issue by TwistedGiraffe** [KSP-RO/RP-1#2215]
Currently, there is some ambiguity in what tech nodes are affected by some leaders and what nodes are not. For instance, does "hypersonic flight" belong to the "flight" category and thus be affected by Ilyushin's -5% penalty? Checking `KCT/TechNodeData.cfg` shows it does not, but the player needs an in-game way to see that. 
Perhaps one way to do it is by another Harmony post-fix, like how we show unlock credit?

**Comment by NathanKell** [comment]
Good idea!
