### ISSUE TITLE
Science return capsule removed

### ISSUE THREAD

**Issue by Tsits11** [KSP-RO/RP-1#2216]
So a long time ago I opened a new issue about soviet probes not showing up in the science tree anymore ! They’re gone ! Eliminated! 
now the same thing happened to the science return Capsule, it’s gone!

I’m sorry but I hardly understand all the coding and stuff I just like to enjoy the game , so can anyone shed some light into what’s going on here ? 
Are these parts being removed because they are no longer supported in the current version of rp1?

**Comment by siimav** [comment]
Yes, the Science return capsule has been removed. It looked bad (IMO) and just didn't mesh with the balancing of other parts.
