### ISSUE TITLE
Crewed records from tourists

### ISSUE THREAD

**Issue by Codelet** [KSP-RO/RP-1#2220]
Still got some records with test animal flight:
- Crewed Altitude Record of 15km
- Crewed Speed Record of 600 m/s
- Crewed Duration Record of 1 day

**Comment by NathanKell** [comment]
Did you update contract configurator to 2.6.2.1 before flying these contracts?

**Comment by ec429** [comment]
Given that there's exactly one of each type, sounds like the old version of each contract had been auto-accepted before you updated; the update only affects what _new_ contracts get offered, not ones already accepted in the save?

**Comment by NathanKell** [comment]
Yep, that sounds like the issue. Contract changes aren't retroactive in that way. Thanks @ec429
