### ISSUE TITLE
Some weirdness with loading procedural probe core

### ISSUE THREAD

**Issue by Codelet** [KSP-RO/RP-1#2224]
Loading the craft with procedural probe core leads to weird issue
![image](https://github.com/KSP-RO/RP-1/assets/26896486/2fa66547-9f5b-49d3-806d-5bebe198119d)
When create new craft the PAW is fine, save craft, load it back - bug.
Also in the console I can see some orange messages appear but console is spammed with message "[FAR v0.16.1.2] Updating Kosmos 2" and this message pushes all other messages outside of the console so fast that it is not really possible to read them.

**Comment by RubenOllesch** [comment]
I have the same issue, not sure what causes it exactly, but as a workaround I am using the procedural avionics, which don't seem to experience the same issue.

KSP 1.12.3.3173 (LinuxPlayer) en-us
Making History 1.12.1
Breaking Ground 1.7.1
[Installed Mods.txt](https://github.com/KSP-RO/RP-1/files/12591694/Installed.Mods.txt)
