### ISSUE TITLE
Tooling inconsistency

### ISSUE THREAD

**Issue by Codelet** [KSP-RO/RP-1#2226]
I have huge science core probe tooled, which generated for me a tooling SM-1 of size 0.8 x 0.8.
If I switch this probe to SM-2 the tooling cost is 12090 (and in tooling window it confirms the SM-2 diameter will be 0.8).
But if I create manually a SM-2 tank 0.8 x 0.8 the tooling cost is 6863.

This is rather suspicious, feels like avionics manufacturer tries to fool me  :)

**Comment by NathanKell** [comment]
I believe @siimav was looking into tooling tech reducers in this regard.

**Comment by siimav** [comment]
I was. But no conclusion was reached on how to handle the reducers so I shelved that idea.

**Comment by NathanKell** [comment]
#2236
