### ISSUE TITLE
Milton Rosen confidence weirdness

### ISSUE THREAD

**Issue by Blothorn** [KSP-RO/RP-1#2232]
First, Rosen's description suggests that he modifies confidence from science, but the implementation (`transaction Reasons { item = ContractReward }` applies it to contract rewards instead.

Second, it seems that this bonus is being double-counted for cumulative confidence: I completed a 75-confidence contract with him active and my actual confidence increased by 82.5 but my "total confidence earned" summary by 90.

**Comment by NathanKell** [comment]
Oh fun, yet another leaders typo.

The other one does sound like a real bug, fixing that too.
