### ISSUE TITLE
'Supersonic Flight' and 'Mach 2 Flight' always show as 'Invalid Situation' 

### ISSUE THREAD

**Issue by brensug** [KSP-RO/RP-1#2242]
'Supersonic Flight' and 'Mach 2 Flight' always show as 'Invalid Situation' – even while running, but they do run as they should.

Assume this is related to [commit 9332d6d](https://github.com/KSP-RO/RP-1/commit/9332d6d782f2e8c949fc17c9a00eafb151983f90) (which made experiments show as 'Invalid Situation' rather than 'Waiting' while flying low).

**Comment by NathanKell** [comment]
Haha this is me being pretty dumb. Will fix, thanks.
