### ISSUE TITLE
(BigBalance) Display of integration time in VAB not taking into account leader stats.

### ISSUE THREAD

**Issue by vallin91** [KSP-RO/RP-1#2255]
When having JPL as a contractor, it does not take the 40% less integration time of avionics in to account when viewing the integration time in the VAB. You have to build the craft to see the 'real' build time.

![vab-integration_time](https://github.com/KSP-RO/RP-1/assets/46173191/5e642475-d91c-42f8-9764-75d23b5419ca)

**Comment by NathanKell** [comment]
I'm pretty darn sure this isn't that it's failing to take leader effects into account, and more that it's not taking _efficiency gain_ into account. Try again when your LC is at max efficiency and see.

**Comment by vallin91** [comment]
You're right. I warped till 100% LC efficiency and it shows the same integration time in the VAB. Is it not possible to show the same figure in the integration info as in the integration tag in the management window? It makes it easier to see the actual time it takes to build without having to actually put it in build queue.

**Comment by vallin91** [comment]
You're right. I warped till 100% LC efficiency and it shows the same integration time in the VAB. Is it not possible to show the same figure in the integration info as in the integration tag in the management window? It makes it easier to see the actual time it takes to build without having to actually put it in build queue.

**Comment by vallin91** [comment]
You're right. I warped till 100% LC efficiency and it shows the same integration time in the VAB. Is it not possible to show the same figure in the integration info as in the integration tag in the management window? It makes it easier to see the actual time it takes to build without having to actually put it in build queue.

**Comment by NathanKell** [comment]
That doesn't really have meaning, because where does it get placed in the integration queue? At the start? At the rear? In the middle? When shown in sequence in the queue, the completion times make sense. Here it has to have a fixed efficiency because the entrypoint can't be known.

**Comment by lpgagnon** [comment]
How about adding a "at x% efficiency" label?
