### ISSUE TITLE
STAR 17 has a completely black texture even after applying the usual fix for SXT textures.

### ISSUE THREAD

**Issue by hallucinogender** [KSP-RO/RP-1#2261]
As the title says. I've used the "Windows_CopyTextures.bat" file to fix the textures for SXT. All other SXT parts, as far as I can tell, have their proper textures now. The STAR 17 solid rocket motor does not.

**Comment by Capkirk123** [comment]
This is an SXT issue. Technically resolved by https://github.com/KSP-RO/ROEngines/pull/232 hiding the SXT Star-17 model
