### ISSUE TITLE
Bug on tech level since last RP1 upgrade

### ISSUE THREAD

**Issue by rub25** [KSP-RO/RP-1#2262]
The R&D basement is fully improved
The science level of instruments @ L2 is now L3 and higher
The researchers have increased to 1000 instead of 600 before.

**Comment by NathanKell** [comment]
The first two are expected. I don't know what you mean by the third.

**Comment by Codelet** [comment]
I assume the yearly price per researcher, which you also mention in release notes.

**Comment by rub25** [comment]
Hello all,
Thank you for your quick feedback.

Concerning the 3rd point :
My satellite initially with video imaging1 & mass spectrometry1 is
collecting science from video imaging3 & mass spectrometry4 ???

Congratulations for the great work you are performing on this mod!

Ruben. (a French fan of KSP RO)


Le jeu. 12 oct. 2023 à 09:29, NathanKell ***@***.***> a
écrit :

**Comment by rub25** [comment]
Also an impact that may come from this issue is that the contract:" First
lunar orbiter & mapper (uncrewed)" doesn't recognize my video imaging 2 on
board as a visible device of level 2 or higher....

**Comment by NathanKell** [comment]
Cheers! :)

I'm very confused by that. Do you have a sfs from before this upgrade, and a current sfs, for me to compare? Nothing should have changed with Visible Imaging or Mass Spectrometry. The only experiments that changed their number were the Photo experiments.

**Comment by NathanKell** [comment]
the sfs is your save file. They live in your save folder (under [your KSP folder]/saves ). persistent.sfs is the active save and there's also all your quicksaves. Please zip and upload your current perssitent.sfs as well as a quicksave from before you updated RP-1.

**Comment by rub25** [comment]
Hello NathanKell,

Sorry for the delay, I was quite busy theses last days.
Here are the 2 sfs files from before and after the RP1 v3 version.
The bug occurs on the vessel called GEO-SCIENCE1

Thanks for your support.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Sans
virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le jeu. 12 oct. 2023 à 21:44, NathanKell ***@***.***> a
écrit :

**Comment by NathanKell** [comment]
Where are they? You can't just use attachments, this isn't an email service. You have to go to this issue on github, start a new comment at the bottom, and drag your files into that box.

**Comment by rub25** [comment]
[sauvegarde rapide BEFORE-AFTER.zip](https://github.com/KSP-RO/RP-1/files/12908731/sauvegarde.rapide.BEFORE-AFTER.zip)

**Comment by NathanKell** [comment]
@rub25 Thanks, I took a look. But both of these saves are from the same version of RP-1, v2.13. The only version difference is an upgrade of KSP Community Fixes from 1.31.0 to 1.31.1.

**Comment by rub25** [comment]
hope this one is from before...
[sauvegarde rapide BEFORE.zip](https://github.com/KSP-RO/RP-1/files/12915954/sauvegarde.rapide.BEFORE.zip)

**Comment by NathanKell** [comment]
No I am saying _both_ saves were from before.

**Comment by rub25** [comment]
This one hopefully is from after...
[sauvegarde rapide AFTER.zip](https://github.com/KSP-RO/RP-1/files/12920464/sauvegarde.rapide.AFTER.zip)

**Comment by NathanKell** [comment]
Pretty sure this is what broke things: https://github.com/KSP-RO/RP-1/pull/2256
Kerbalism uses the module title rather than the experiment ID when storing which experiment is active. Because the experiment titles changed on the Video Imaging experiments, the configuration settings for them broke, which means the experiment activation got out of sync. So that's why you ended up with the wrong experiments being active on that vessel. Going forward any new vessels you create (or load and start integrating), double-check their experiments are configured correctly. Sorry about this.
