### ISSUE TITLE
Early Commercial Applications program is inconsistent between admin and mission buildings

### ISSUE THREAD

**Issue by Codelet** [KSP-RO/RP-1#2264]
In administration building there is "Early Commercial Applications" program.
In the first ("All") tab of mission building there is "Commercial Application Satellites" which contains most of the contracts from the program but is missing the Early Navigation Network and Early Communications Network contracts.
These contract I could not find anywhere else.

Checking only the "All" tab when program is not active.

**Comment by NathanKell** [comment]
Could not repro the Nav Network contracts not showing up. The comm network contracts were under the Comm Network folder in the All tab, fixed that.

**Comment by NathanKell** [comment]
Oh. You need to update Contract Configurator.

**Comment by NathanKell** [comment]
Sorry, you need to update to 2.6.5.2 once it's on CKAN. I had a bug. :D

**Comment by Codelet** [comment]
Updated to 2.6.5.2- all fine, can see network contracts now, thanks :)
