### ISSUE TITLE
Early Navigation Sat Network 3 vs 4 contract has same parameters

### ISSUE THREAD

**Issue by peternewman89** [KSP-RO/RP-1#2269]
Both the 3 and the 4 NavSat Network contracts have the same parameters, with 100 units of NavSat payload and AP below 1,200km, PE above 700km, and low eccentricity. The 3 sat network should likely be higher, or have more payload, or in some way be different to account for fewer launches, the way the CommSat contract is configured.

**Comment by NovemberOrWhatever** [comment]
The reward, however, is different. You get 50*3 reputation for the three-satellite one, or 50*4 reputation for the four-satellite one. I believe this is intended

**Comment by NathanKell** [comment]
The orbits for navsats are not "as high as you need to be to have LOS to other satellites" like a comm sat, they're "what is a good orbit for a navsat". So that shouldn't change. I'm reducing the payload requirement for the 4-sat network however.
And as November says, the reward _does_ scale.
