### ISSUE TITLE
Starting research speed is too slow

### ISSUE THREAD

**Issue by Codelet** [KSP-RO/RP-1#2271]
With 20 researches taken from start the initial nodes are completed in:
- Post-War rocketry testing: 243 days
- Early Solid Rocket Engines: 243 days
- Post-War Materials Science: 486 days
- Early Tracking Systems: 486 days

Which feels way too much tbh. Also it is rather hard to hire more researchers if I want to have both WAC-Corporal and V-2 rockets from the start. I'll need 10 engineers for WAC/Aerobee and 70 for V-2 and even if I don't max engineers up, it is still not much more researchers I can get.

If I say "no" to V-2 rockets,. I can hire 50 researchers from the start. With 50 researchers the research would complete in:
- Post-War rocketry testing: 121 days
- Early Solid Rocket Engines: 121 days
- Post-War Materials Science: 243 days
- Early Tracking Systems: 243 days

Which is still a lot and the income gets rather low so no much hope to get more researchers fast. And also this leaves me with only WAC which is not very useful :)
To launch Aerobee with bio sample I need at least 3 of 4 nodes above (better all 4). And w/o it I can't get above 30 science to see the speed up from efficiency. 

All this doesn't feel correct. Researching initial nodes for several years is weird. If it is as intended could you give me some hints on how to start now because I am completely lost,

**Comment by Test-Account-KSP** [comment]
The best place to ask for this type of advice is the RO/RP1 discord.

https://discord.gg/earfBEbC

**Comment by NathanKell** [comment]
Yep, this is an #rp1-career-help question. It's definitely the case that the early game is slower now than in the last release.

**Comment by Codelet** [comment]
Got it, thanks :)

**Comment by Codelet** [comment]
@NathanKell sry to bother, but are you really sure-sure it should be **that** slow? With 250 researchers the Sat Era Material Science takes 280 days to finish.
