### ISSUE TITLE
Kerbalism experiments are unaware of Principia's tilt

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/RP-1#2276]
from https://discord.com/channels/319857228905447436/620690446540341261/1163695904298127410

- Some kerbalism experiments have inclination constraints.
- Principia tilts the universe based on the inclination of the "current" body
- Kerbalism isn't aware this tilt happens, so the inclination it thinks a vessel is in varies with where the player is, sometimes making some experiments unable to run when they should (and even vice-versa!)

example: probe in moon orbit, currently loaded:
<img width="316" alt="Screenshot 2023-10-17 at 17 58 12" src="https://github.com/KSP-RO/RP-1/assets/5061230/e8644178-f796-4415-be3a-50a85057fd7c">

same probe, while a vessel in venus orbit is loaded:
<img width="319" alt="Screenshot 2023-10-17 at 18 01 34" src="https://github.com/KSP-RO/RP-1/assets/5061230/6f3c08f2-48c7-4b04-b2a6-5d22357b277a">

**Comment by NathanKell** [comment]
Fixed in next Kerbalism.

**Comment by NathanKell** [comment]
See also https://github.com/KSP-RO/ContractConfigurator/releases/tag/v2.6.6.0
