### ISSUE TITLE
Hangar should not need to be upgraded for "Propellant GSE"

### ISSUE THREAD

**Issue by ghost** [KSP-RO/RP-1#2281]
The Hangar needs to be upgraded every time a rocketplane needs some fuel that has not been added to the LC.  This adds micromanagement, but doesn't serve any meaningful purpose. For rocket LC's the types of propellant can be used to distinguish between different LV's and ensure that each LV is built on its own LC, but there is only one hangar for all planes. I suggest to make all types of fuels available at the Hangar in infinite/very high amounts.

**Comment by Clayell** [comment]
Not really realistic. The hangar already has very large size requirements, which is the distinction that usually puts LCs apart. A hangar (especially one meant for **rocketplanes**, as most planes do have similar fuels) cannot have every single type of fuel, and it cannot hold infinite amounts of fuel. The only mercy that the game gives you is infinite Kerosene, which makes sense as it is the most common jet engine fuel and can be assumed to have a direct pipeline to some oil refinery. Luckily, refurbishing a hangar to accept new fuel types does not take very long 😄.

**Comment by Capkirk123** [comment]
Correct, the Hangar gives infinite kerosene, and I believe there is a minimum required resource amount to require GSE, which means very small amounts of other resources will be allowed. However, loading large amounts of exotic/cryogenic propellants for X-planes will require special handling and therefore some modification of the hangar facilities.

This is intended behavior.
