### ISSUE TITLE
Uncrewed (but crew capable) test flights in Crewed Orbit program have unstable contract requirement

### ISSUE THREAD

**Issue by Karhgath** [KSP-RO/RP-1#2282]
The "have space for 1 crew member" requirement for uncrewed sub/orbital testflights keeps changing and being validated/invalidated every time you stage or a situation changes for the contract, which can leave the contract unable to complete when you touch down and recover.

I saw the issue a few times before but forgot to report (and sometimes it is back to green when you touchdown so it still works), and I do not have a specific save or screenshot, but this reddit post (from another user) with video highlights what happens:
https://www.reddit.com/r/RealSolarSystem/comments/17djutw/what_is_changing_when_i_stage_that_is/

My guess is that it is related to "disableOnStateChange = false".

**Comment by Teykn** [comment]
> My guess is that it is related to "disableOnStateChange = false"

Don't think so. "disableOnStateChange = false" makes it so if the parameter is completed or failed, the parameter *isn't* disabled, so it can go back to being incomplete. 
Not sure if a failed parameter can return to being incomplete though. That's probably a separate issue.

**Comment by Karhgath** [comment]
On the other hand, during the contract execution, you cannot go from Uncrewed to Crewed. If on the flight scene load you are valid, it should be checked and remain checked, not be reevaluated every state change?

I agree the root cause must be something else to actually evaluate the parameter incorrectly in alternance on state change.

**Comment by Karhgath** [comment]
Just realized you could just ditch the capsule on the pad then...

**Comment by Karhgath** [comment]
From repro-ing another issue (https://github.com/KSP-RO/RP-1/issues/2294), I triggered this only by adding the Mercury Landing and Control Module to the craft, without it it never triggered this issue.

![screenshot539](https://github.com/KSP-RO/RP-1/assets/440648/2a139fd4-917a-4e2f-b749-bd1be2e31f56)

**Comment by Joesk** [comment]
This is also happening with the MK1 pod.
![screenshot224](https://github.com/KSP-RO/RP-1/assets/23213189/b8dde577-15f4-494d-ac31-401eb0b0e30d)

**Comment by siimav** [comment]
I believe this happens when some staged-off parts explode during re entry. I wasn't able to replicate this because I was running the game with Ignore Max Temperature cheat enabled. Would be great is someone could confirm this theory.

**Comment by siimav** [comment]
Please test with this: https://github.com/KSP-RO/ContractConfigurator/pull/30
