### ISSUE TITLE
Interplanetary contract issues

### ISSUE THREAD

**Issue by Test-Account-KSP** [KSP-RO/RP-1#2288]
- Venus Landing contract is bugged. It can be taken twice, but there is no confidence reward for the second one.  It's marked "CAPSTONE" and gives reputation again.
- Mars Landing has the same issue. The second contract is marked "Required" and also gives only reputation. 
- Crewed Targeted Moon Landing suffers from the same issue.
- Mercury, Pluto and Charon landings as well. 
- Titan Rover is an optional contract, but gives no confidence.

**Comment by NathanKell** [comment]
Closed via #2290
