### ISSUE TITLE
"Crew Updates" information popup prevents user from stopping time warp.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-RO/RP-1#2292]
Recently a new popup window was added that tells the player that a crew training event has finished.  It appears to have been to inform the user that time warp can stop now.  But if the user was time warping Manually (i.e. using hotkeys comma and period), the informational popup is preventing the user from being able to stop their time warp, making them "blow past" the timestamp even farther as they try to figure out why time warp is "stuck on".

To re-create:
1 - Start some astronaut cockpit training of some sort.

2 - Start time warping manually with "period" hotkey (or whatever you've mapped the key to).

3 - Time warp long enough to hit the end of the training you started in (1) above.

4 - A popup appears saying "Crew Updates" with information in it like is shown in the screenshot below.

5 - Try to stop your manual time warp by hitting the comma hotkey (or whatever you have mapped the hotkey to if it's not comma).

6 - You can't.

The natural thought process for a user is "Oh, I should dismiss that popup that just appeared, but I'd better stop the clock first since I'm warping ahead so quickly...."  And it wouldn't be natural to do it the other way around, thinking, "Oh, I should dismiss this window while still at fast time warp, THEN stop warping.." (which is how you end up having to do it the way it is now, but it takes a little bit to realize that.)

In my case it occurred while I was at max warp speed and in the several confused seconds it took to realize it was the popup window itself that was making the time warp get stuck,  3 "game months" had passed.

====

(---- guess as to a possible cause ---- )

My guess would be that when this kind of window was added, it uses a KSP input lock mask, and it happened to contain the mask bit that disables time warp controls.  (I would also guess it was tested using KCT"s time warping and not tested on what happens with manual time warping.)

![bug_timewarp_input_lock](https://github.com/KSP-RO/RP-1/assets/5216848/866a7396-ec92-4a16-b128-26a20fd7b7f0)

**Comment by NathanKell** [comment]
This was already fixed for training dialogs but not other crew updates.
