### ISSUE TITLE
Unable to finish Orbital Test Flight (Uncrewed) contract due to landed capsule not registering as "Return Home Safely".

### ISSUE THREAD

**Issue by Karhgath** [KSP-RO/RP-1#2294]
Seems to be 100% reproducible for this craft - I used a very minimalist Mercury without all the parts except heatshield. When it lands, it does not register that it is landed safely, so cannot end the contract other than F12. 

Craft file and save included, here are different tests I did - even tried crewed with 8h resources and same thing. 

Some images of 3 different attempts (the last 2 are sims, last one is crewed)
![screenshot535](https://github.com/KSP-RO/RP-1/assets/440648/8be2d905-e22f-459a-8bf1-8a608226dcd4)
![screenshot536](https://github.com/KSP-RO/RP-1/assets/440648/4df2c2f1-de5e-46fa-a587-30a9750e8f30)
![screenshot538](https://github.com/KSP-RO/RP-1/assets/440648/09d342e8-352c-4d1e-ab78-e761c3e46224)

Save:
[_afterLaunchReturnCapsuleBug.zip](https://github.com/KSP-RO/RP-1/files/13301237/_afterLaunchReturnCapsuleBug.zip)

Craft:
[Mercury Uncrew [Mercury]R Thanos.zip](https://github.com/KSP-RO/RP-1/files/13301242/Mercury.Uncrew.Mercury.R.Thanos.zip)

PS: Also tested by adding the Mercury Landing and Control Module, in case for some reason it had an impact, but no dice. Even worse, it triggered: https://github.com/KSP-RO/RP-1/issues/2282

![screenshot539](https://github.com/KSP-RO/RP-1/assets/440648/315dbb21-8fac-4775-88cf-703ea3a76ac5)

**Comment by Karhgath** [comment]
Other contracts did not seem to exhibit the same behavior, even if using the same craft file. Not sure what happened with this contract or it was something situational.

**Comment by siimav** [comment]
The real problem is that "Stay in specified orbit for the duration" parameter is already ticked green while the vessel is sitting on the launch pad. Looks like somehow a previous vessel completed it and for whatever reason it doesn't get recalculated for the new vessel.

**Comment by siimav** [comment]
Did some more digging and there's 2 separate issues here.
The "return home" parameter doesn't complete because "crew capacity" flipped to unmet status. In some cases the contract widget doesn't update it immediately even though internally the status has already changed.
The other issue is `All` parameter getting stuck in completed status from other vessels/launches. This is due to it having `disableOnStateChange = true` coupled with the fact that it doesn't derive from `VesselParameter` and thus doesn't know how to track multiple vessels at the same time. Unfortunately there doesn't appear to be a `VesselParameter` that would serve as an alternative for such wrappers.

**Comment by siimav** [comment]
Please test with this: https://github.com/KSP-RO/ContractConfigurator/pull/30

**Comment by siimav** [comment]
"Stay in specified orbit for the duration" group needs to be rewritten in the old-style Duration wrapped inside Orbit since https://github.com/KSP-RO/ContractConfigurator/pull/29 should properly support it now.

**Comment by Karhgath** [comment]
Tested the above fix from my posted save, I am also nearing orbit in another one and will try there later

- Normal launch and recovery worked. The requirements were not fluctuating during the whole mission, like when staging.
- Normal launch, switching to another vessel, and coming back worked. The requirements were invalidated on the other vessel, but came back green when switched back. Recovery worked.
- Normal launch, changing back to space center and fiddling around, and coming back. Working perfectly.
- Launched with the Mercury control module which caused https://github.com/KSP-RO/RP-1/issues/2282 before. No issues with fluctuating requirements.

![image](https://github.com/KSP-RO/RP-1/assets/440648/1f9abc06-76f1-4c34-a9b9-06ba66d257e0)

So both issues seem fixed now.

I will keep using the new CC in my current game and see if it's stable as well.
