### ISSUE TITLE
Engineers do not go idle if any vessel is rolled out

### ISSUE THREAD

**Issue by siimav** [KSP-RO/RP-1#2298]
![Empty](https://media.discordapp.net/attachments/512556346869284864/1173067073199542312/image.png?ex=65629ad8&is=655025d8&hm=ad01a4c7b08b0c0cc3032f6fc88140d35f3958690d6cdd115a22b40532832e3c&=&width=705&height=418)
![Rolled out](https://media.discordapp.net/attachments/512556346869284864/1173067286685429881/image.png?ex=65629b0b&is=6550260b&hm=8b2e69794be01d3800a4a42191e67929457aa1a127dc727f3fa7a69f75b8b0af&=&width=705&height=422)

**Comment by Codelet** [comment]
Same as https://github.com/KSP-RO/RP-1/issues/2277 I guess
