### ISSUE TITLE
 Science collectable below 40km altitude, v3.2.1.0 release

### ISSUE THREAD

**Issue by lgusar** [KSP-RO/RP-1#2299]
Fresh installation of both KSP 1.12.3 and RP1 through Express installation. Additional mods Principia, Janitor's Closet, kOS, kOS Astrogator.

With the new update, science can be collected below 40km.

![image](https://github.com/KSP-RO/RP-1/assets/24841366/7d82c4fc-940a-41c6-9ef0-fc59bf2a3dde)

**Comment by siimav** [comment]
Fixed in [Kopernicus release-193](https://github.com/Kopernicus/Kopernicus/releases/tag/release-193)
