### ISSUE TITLE
Some engines descriptions like Agena B and D restart penalties are overwritten by RP-1, but descriptions should be maintained in RO.

### ISSUE THREAD

**Issue by Karhgath** [KSP-RO/RP-1#2308]
While investigation why Agena B and D description is different from RO configs

Config:
https://github.com/KSP-RO/RealismOverhaul/blob/32ab62ccbde3600b6c22c5bd78d1161ef1f5c08e/GameData/RealismOverhaul/Engine_Configs/Agena_XLR81_Config.cfg#L395
https://github.com/KSP-RO/RealismOverhaul/blob/32ab62ccbde3600b6c22c5bd78d1161ef1f5c08e/GameData/RealismOverhaul/Engine_Configs/Agena_XLR81_Config.cfg#L461

In game:
![image](https://github.com/KSP-RO/RP-1/assets/440648/fd57a90a-27c5-49f5-9600-b859ea97e355)

I figured out that TREE-Engines.cfg overwrites many engines descriptions.
https://github.com/KSP-RO/RP-1/blame/ad4f136d5982cb9fc35216fa4ae24007d8c69292/GameData/RP-1/Tree/TREE-Engines.cfg#L5424

Would the proper fix be to remove all description in this file, not sure if any are necessary (e.g. not defined anywhere else)?

**Comment by lpgagnon** [comment]
easy fix would be to get rid of https://github.com/KSP-RO/RP-1/blob/ad4f136d5982cb9fc35216fa4ae24007d8c69292/Source/Tech%20Tree/Parts%20Browser/tree_engine_cfg_generator.py#L101-L103

(if there _are_ engine configs lacking descriptions, that'd be a RO bug to fix separately)

**Comment by Capkirk123** [comment]
resolved by https://github.com/KSP-RO/RP-1/commit/fc28721c22f40678f30d6c6a1b9c4d14ce131694
