### ISSUE TITLE
Cosmic Ray Science Experiment not including lesser versions of experiment

### ISSUE THREAD

**Issue by norcalplanner** [KSP-RO/RP-1#2310]
Discovered during the race that the Cosmic Ray Science 2 experiment does not also include Cosmic Ray Science 1, which is different from most other higher level science experiments. Verified in the .cfg that the language for including lesser experiments isn't present in any of the advanced cosmic ray experiments. Seems like an oversight.

**Comment by norcalplanner** [comment]
Description text in the EOS cosmic ray satellite contract also references that the contract can be completed with either a geiger-muller counter or scintillation counter, when the scintillation counter currently will not complete the contract.

**Comment by siimav** [comment]
Should be fixed in c89ec8a610e47e5531bc1a8a29ae9a1f50a183a6
