### ISSUE TITLE
Lunar Impactor contract fails at high impact speeds

### ISSUE THREAD

**Issue by Amselfass** [KSP-RO/RP-1#2311]
**Environment:** RP-1 v3.2.1 on KSP 1.12.3

**Steps to reproduce:** Accept the *Lunar Impactor* contract and plot an impact trajectory with a TLI dv of 3700 m/s or more. Wait until the vessel descends below 3500 m AGL. The attached screenshot shows this situation.

![Screenshot 2023-12-09 130207](https://github.com/KSP-RO/RP-1/assets/46572014/6bb490fb-d4fd-4be7-bb8e-37f32bc29d60)

**Expected behaviour:** The *'Altitude (terrain): Below 3500 m'* parameter should be marked as fulfilled.

**Observed behaviour:** The parameter takes a short while to update, and the vessel will impact beforehand, causing the contract to fail.

Would there be a problem with raising the altitude requirement a bit?

**Comment by Test-Account-New** [comment]
I've definitely hit the moon at 4km/s with no such issues

**Comment by siimav** [comment]
The parameter should update every 0.1s which in theory should leave plenty of margin for it to trigger as long as the player isn't running 10x timewarp.

**Comment by Amselfass** [comment]
No timewarp in the screenshot.

**Comment by siimav** [comment]
Probable fix added in df4b2f580c477e539c042d1a7b26f325cd4ee8c0
