### ISSUE TITLE
Quicksaves break down physics during Timewarp

### ISSUE THREAD

**Issue by beans0256** [KSP-RO/RP-1#2322]
I and some others have been having an issue after making and loading a quicksave. Once quicksaves have been made and loaded, any timewarp over 4X speed will cause the targeted object to stop moving in space, all planets to stop rotating, and any craft you are playing in orbit will quickly destabilize. I've attached screenshots of messages sent to the RP1-Support channel on Discord and the videos and screenshots sent there. Everyone with quicksave issues also are on installs that are recent (as old as November 2023)

![Screenshot 2024-01-08 194359](https://github.com/KSP-RO/RP-1/assets/109005596/db649eed-050c-4390-aa87-35666340f6b5)

https://github.com/KSP-RO/RP-1/assets/109005596/0624512b-d748-4a0e-a8e7-5d7530b90df2

![Screenshot 2024-01-09 163715](https://github.com/KSP-RO/RP-1/assets/109005596/a63e51dc-dab7-4901-bf89-607509c97bba)

![Screenshot 2024-01-09 163659](https://github.com/KSP-RO/RP-1/assets/109005596/2cd948f9-9d2f-43b8-9b67-c8dec3a511ac)

![Screenshot 2024-01-09 163829](https://github.com/KSP-RO/RP-1/assets/109005596/e49b2a0f-19bc-4d64-9486-7c085a3540c9)

**Comment by beans0256** [comment]
Not everyone has the same issue, but they all revolve around quicksaves

**Comment by beans0256** [comment]
No updates :(

**Comment by beans0256** [comment]
Accidentally closed

**Comment by siimav** [comment]
Not 100% sure if the issues are related but it's possible that https://github.com/KSP-RO/RealismOverhaul/pull/2940 will also resolve this.
