### ISSUE TITLE
Game Crashed in various scenarios

### ISSUE THREAD

**Issue by QuackQuackZA** [KSP-RO/RP-1#2329]
I need help please. I don't really know where to go from here.

I have played RP-1 for a few days. From day 1 there has been several PC crashes (not game crashes) every day. Typically when I start to simulate/launch, or several minutes into a launch and especially when switching to map view. It also happens after a while of just sitting at the space center. It is not linked to a specific craft, it has happened to all my craft. It also doesn't always crash. The laptop just goes black (as in the laptop is off).

I followed the express install instructions using CKAN. I have reinstalled KSP, and RP-1 express install. I thought it may be a hardware issue. Below is a comparison of RP-1 at FPS limited to 180 and 120 as well as a Shadow of the Tomb Raider at max everything. I ran the benchmark 4 times in a row, and the system had higher utilization, but no issues. Considering the results I don't think it is a thermal shutdown, but more likely a memory issue? Due to the nature of the crash there is no windows error log apart from Event ID 41 Kernel Power and the subsequent 6008, which is generated after a 41 ID. I have not yet tried running lower res packs. I will try that later today, but would prefer to run the high res packs as this laptop should be able to crush it.

The laptop is a high performance gaming laptop (Desktop replacement level, specs below), ROG Strix G18, and it is stock. I have not changed any settings on it (e.g fiddling with the page file size, VRAM capacity, etc.), simply used the built-in performance modes. These test were run in its "normal" mode, no boosting or anything.

The datapoint on the graph shows the parameter prior to crash.

KSP RP-1 FPS 180 (initial trend is just PC starting and loading the game, flatline is in the game)
<img width="1009" alt="image" src="https://github.com/KSP-RO/RP-1/assets/157540166/562a6ab5-c7dc-427a-afd7-7adbbc2a5fd6">

KSP RP-1 FPS 120 (The dip in GPU usage was when I tabbed out of the game)
<img width="1024" alt="image" src="https://github.com/KSP-RO/RP-1/assets/157540166/9e74935d-81a6-4078-a208-2c12d2e65d44">

Shadow of the Tomb Raider FPS 120-170
<img width="1011" alt="image" src="https://github.com/KSP-RO/RP-1/assets/157540166/54e32af0-98be-4484-9d2f-41755543c921">

PC Specs

OS Name	Microsoft Windows 11 Pro
Version	10.0.22621 Build 22621
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Manufacturer	ASUSTeK COMPUTER INC.
System Model	ROG Strix G834JZ_G834JZ
System Type	x64-based PC
System SKU	
Processor	13th Gen Intel(R) Core(TM) i9-13980HX, 2200 Mhz, 24 Core(s), 32 Logical Processor(s)
BIOS Version/Date	American Megatrends International, LLC. G834JZ.321, 2023-10-24
SMBIOS Version	3.5
Embedded Controller Version	0.69
BIOS Mode	UEFI
BaseBoard Manufacturer	ASUSTeK COMPUTER INC.
BaseBoard Product	G834JZ
BaseBoard Version	1.0
Installed Physical Memory (RAM)	32.0 GB
Total Physical Memory	31.6 GB
Available Physical Memory	19.1 GB
Total Virtual Memory	34.8 GB
Available Virtual Memory	15.5 GB
Page File Space	3.13 GB
Page File	C:\pagefile.sys
GPU	NVIDIA GeForce RTX 4080 Laptop GPU 12 GB
Resolution	2560 x 1600 x 239 hertz

[error.log](https://github.com/KSP-RO/RP-1/files/14111250/error.log)
[KSP.log](https://github.com/KSP-RO/RP-1/files/14111253/KSP.log)

Let me know if you need anything else. Would really appreciate assistance.

**Comment by siimav** [comment]
Honestly I refuse to believe that some issue with Unity, KSP or this modpack can cause a system to outright shut down. Have you already tried limiting fps to 60 or applying some profile that limits CPU and GPU power to more sane levels?

**Comment by QuackQuackZA** [comment]
I don't think so either. I checked again, there is no boosting of any kind happening. I did what you said and locked the FPS at 30 and it still happened.

I decided to actually go to the overclocking interface for Armoury crate. I didn't change any base clock speeds, but what I did was set fan speeds at max. It ran significant longer before crashing, with lower temperatures, as in 10-15 °C lower. Eventually though, after like an hour, the temperatures did climb back up  and it crashed again. However, I was not at the computer when this happened, so possibly could have gone to sleep and change the performance mode back to the base mode.

What I find confusing is, prior to changing the fan speeds I have not touched the overclocking features the laptop comes out with, or unshackled the system in any way. If it really is over heating, then it is not showing any warnings. Also I don't think it is overheating, as the temperatures and power levels shown in the logs previously is very normal for this system.

I remember back in the day when I modded ME3 there was an issue with the high res textures I was using. That was on an older system, but that was with the filling system that was being used, and the system couldn't actually copy files that size, e.g. maximum file size for NTFS is 4 GB and fat32 was like 1.2 GB. Something along that line. But I haven't been able to find anything that can support that theory, and considering the system I am using now that shouldn't be an issue. And there is still the issue, that benchmarking on a game that places significantly more load on the GPU, there was no issue.

I am just kinda out of ideas here.

**Comment by QuackQuackZA** [comment]
I also now tried switching off Windows Accelerated GPU Scheduling, as I heard it can cause issues with the drivers/armoury crate. It significantly lowered the GPU utilization and slightly increased the CPU utilization (which is expected), but it still crashed. But there are spikes. I am trying to speak to the hardware support people as well, but they haven't gotten back to me yet.

<img width="1153" alt="image" src="https://github.com/KSP-RO/RP-1/assets/157540166/ccd744e6-e75b-4d8f-abb0-8338279462b0">

**Comment by siimav** [comment]
The thing you aren't monitoring is SSD temperature. Might wanna double check that too.

**Comment by QuackQuackZA** [comment]
It is rock steady at 41 °C and health at 100% still. But that is through windows Storage manager, so don't know how good that is for monitoring purposes. I also check the read/write activity while running the game. Barely does anything. So can't imagine that it is overheating.

**Comment by siimav** [comment]
No news so I'm closing this.
