### ISSUE TITLE
Missing Parts for APP

### ISSUE THREAD

**Issue by GPaws** [KSP-RO/RP-1#2341]
Thanks for such a fantastic realistic mod although its sad to say im missing parts of airplane plus can you please help me to fix this i cannot try to recreate my bell x 1 craft

**Comment by nick13dc** [comment]
Same.  I am missing the XLR engine.

**Comment by nick13dc** [comment]
After a lot of undignified behavior ie cursing... I found that the assets for those engines are in RO Engines and are not supported in the current express installation.  I downloaded the file copied it over into the game folder; I now have excess to the parts.  I broke my current save, put I now have the same parts as others on RP1 playthroughs.  If those same assets are now available somewhere else I do not know; or if the missing assets are a bug for people that are just now downloading RP1.

**Comment by Capkirk123** [comment]
As you have noticed, Airplanes plus does not contain any XLR11s, that is a part from ROEngines.

ROEngines is very much fully supported by the express installation, and is in fact an integral part of the express install. I suggest you reinstall RP-1 following [These instructions](https://github.com/KSP-RO/RP-0/wiki/RO-&-RP-1-Express-Installation-for-1.12.3)
