### ISSUE TITLE
Absurd amount of confidence for GEO contract right after taking

### ISSUE THREAD

**Issue by byt3c** [KSP-RO/RP-1#2342]
When selecting geostationary network program in 1965 and picking first optional contract for geostationary satellite there is 1475 confidence reward for 1889 days after expected contract fulfillment date. Not sure where it came from. Using 3.5 continuing career from RIS 2023 upgraded from v3.3 
![geo](https://github.com/KSP-RO/RP-1/assets/38114978/d280513f-60de-4d3c-a0e4-67b71fcc9f52)

**Comment by siimav** [comment]
Yeah, looks like the timer is shared with contracts from the previous commercial sats program. Probably need to set up separate timers but that only works when the programs cannot be accepted at the same time.
