### ISSUE TITLE
[HarmonyPatch] HarmonyTranspiler Problem

### ISSUE THREAD

**Issue by tinygrox** [KSP-RO/RP-1#2345]
Is this really going to work as intended? As far as I understand it, both `fromPart` and `pCrew` are simply values being retrieved, rather than references to the respective fields. Thus, I'm not entirely sure how this is expected to function as desired, though I could be mistaken. 🤪 

https://github.com/KSP-RO/RP-1/blob/1001698630954e124e8320808742a63ee57d9351/Source/RP0/Harmony/FlightEVA.cs#L57-L67

**Comment by siimav** [comment]
Looks like the idea is that doing EVAs while the vessel is suborbital, doesn't register it in the flight log. Sounds like easy enough to test.

**Comment by tinygrox** [comment]
Forget it...
