### ISSUE TITLE
Starting scenario has no effect until restart if non-preset options are used

### ISSUE THREAD

**Issue by brensug** [KSP-RO/RP-1#2348]
I found changing Kerbal Renamer config causes the 1957 start scenarios to have no effect – I get a normal 1951 start with no LCs/programs/research. If I then go back to main menu and make a new save with one of the preset 'difficulty' options, the scenarios still have no effect. This persists until the game is restarted.

**Comment by siimav** [comment]
Does applying a scenario work if you do it straight after starting the game up? I.e you don't load into a save or start another game without a custom scenario selected.

**Comment by siimav** [comment]
Please try the fix in https://github.com/KSP-RO/RP-1/pull/2349#issuecomment-2054114983

**Comment by brensug** [comment]
Yep, looks like that's done it. Using the scenarios with custom options works, and making another new save with a different scenario or no scenario works too.
