### ISSUE TITLE
Leaders retiring during Simulation don't revert

### ISSUE THREAD

**Issue by pctr2142** [KSP-RO/RP-1#2354]
When running a longer sim, for instance a interplanetary mission testing, if the time passing is long enough for a leader to retire they stay retired when you revert and exit the VAB. Didn't seem to affect the number of days remaining unless it was long enough to cause them to retire.

**Comment by siimav** [comment]
The good old `Planetarium.GetUniversalTime()` bug strikes yet a again, albeit in a slightly different form. I bet this bug will even exist in pure stock KSP.
