### ISSUE TITLE
Unable to see delta V calculations

### ISSUE THREAD

**Issue by Ender436** [KSP-RO/RP-1#2369]
Hello, I'm relatively new to realism overhaul, but I've been playing lately, and as I began to get further than LEO, whenever I'd try to make a maneuver node it was incredibly difficult because I can't find my delta v in any of the usual menus like in stock, and I'm not seeing any way to see it. This especially affects my ability to execute maneuvers, as I can't tell how long a burn is or anything. Any help would be great!
I'm on 1.12.5, followed the installation instructions exactly.

**Comment by Capkirk123** [comment]
The stock deltaV indicators are disabled because they do not provide accurate readings in RO. Use the Mechjeb DeltaV window.
