### ISSUE TITLE
Idea:Add back fund-giving commercial contracts for late game.

### ISSUE THREAD

**Issue by Not-a-flying-brick** [KSP-RO/RP-1#2370]
Although I understand that going programs for most of the space center’s income is a good idea, we only have finite number of programs, and it mostly runs out in 1980s for this version of RP-1.
Why not add back repeatable fund-giving commercial Nav/Com/Wea satilites so that a space agency could self sustain late game after dismantling some complexs and firing most of their employees after they run out of programs？
I knew that devs are adding new programs over time,but it is finite amount of years, after all.
These contracts should be:
1.very unrewarding in terms of funds so that people will not abuse them when they still have income from programs(Like, even some versions of delta 2 cannot be cheap enough to get enough profit to sustain the agency)
2.Kept to barebones (for example, cancel the tundra and monloya and geostationary versions of those contracts, make those generic contracts’ orbit parameters more varied instead)so it doesn’t affect normal gameplay before 2000s

There is also an idea of adding fund-giving _Earth observation satilites_ contracts,to symbolize large spy satilites operating in LEO.But instead of bringing the photography 3 experiment, bring a satilites bus (using KH-9 or shrunken Almaz model)just similar to the Nav/Com/Wea ones.Should be low-rewarding to keep people sticking to existing programs if they have, but more rewarding than the Nav/Com/Wea contracts because, well, it’s used by the government.

Adding a medium-reward but cool-down High orbit commercial satellite contract will also be possible.However make those target orbits randomly in Earth SOI, Pergee beyond geostationary heights to limit feasibility by using a cheap vehicle.

It is Just an idea.Don’t consider doing it if it cost the devs something more than copying the cfgs from the legacy version.

**Comment by siimav** [comment]
Honestly I don't see this happening. The more likely outcome is that we allow some programs to be accepted again. Constellation maintenance with σκοπός could be a nice use case here.

**Comment by Not-a-flying-brick** [comment]
Good idea.

「siimav ***@***.***>」在 2024年6月3日 週一，19:14 寫道：

**Comment by Capkirk123** [comment]
The Skopos beta (which can be found in the RSS/RO Discord server) currently provides reputation for maintaining satellite constellations. I do intend for them to provide funds as well in the future, although that may need further integration with RP-1.
