### ISSUE TITLE
Simulation Revert to Launch removes procedural part configs

### ISSUE THREAD

**Issue by KerballOne** [KSP-RO/RP-1#2371]
When Reverting to Launch during a KCT Simulation, the procedural parts (avionics, tanks, and wings) revert to their default original size and shape.  Their positions are preserved.  The procedural fairings are preserved, but are "opened" as if previewing in the VAB.
This rocket is the V-2 using the parts and configs from the [Early Career Tutorial](https://github.com/KSP-RO/RP-1/wiki/Building-a-Downrange-Rocket).
![Screenshot 2024-05-28 134721](https://github.com/KSP-RO/RP-1/assets/161400249/820f7e67-4513-4a9e-9d4c-121e46cef2bf)
![Screenshot 2024-05-28 134802](https://github.com/KSP-RO/RP-1/assets/161400249/0c25c68c-3200-4c1b-b046-a87f7b0bb4ea)

**Comment by siimav** [comment]
Never seen such an issue before. Did you follow the install guide and are all the mods up to date?
https://github.com/KSP-RO/RP-1/wiki/RO-&-RP-1-Express-Installation-for-1.12.3

**Comment by KerballOne** [comment]
Yes, following the guide to the letter.  And doing the career mode also with the guide.  All mods are up to date.

**Comment by siimav** [comment]
You have Tweakscale and its companion mods installed which are most likely the cause of your issues.

**Comment by KerballOne** [comment]
Removed:
```
	TweakScale - Rescale Everything! (TweakScale v2.4.7.5)
	TweakScale Companion for ReStockPlus (TweakScaleCompanion-ReStockPlus v1.1.0.0)
```

I have tried having only `TweakScale Rescaled Redistributable (TweakScaleRescaled-Redist 3.2.3)`
which is required based on [the guide section 3](https://github.com/KSP-RO/RP-1/wiki/RO-&-RP-1-Express-Installation-for-1.12.3#3-ckan-popups) _"Ferram Aerospace Research Continued requires TweakScale-Redist, which can be provided by multiple mods" Click the 2nd option. (TweakScale Rescaled Redistributable)"_
Also, I even tried using only `TweakScale Redistributable (TweakScale-Redist v2.4.8.3)`

No change in behavior.

**Comment by KerballOne** [comment]
I uninstalled RP-1 and all dependencies and all Tweakscale mods... then went through the _"RO & RP 1 Express Installation for 1.12.3"_ again.  
Still, no change in behavior.

**Comment by KerballOne** [comment]
Yes, that mod was removed.

**Comment by siimav** [comment]
I don't even recognize half of those mods. This issue won't occur if you set up the Express install and didn't add a ton of other mods into the mix. TBH it's up to you to figure out which one of those about 100 of so mods is the culprit.

**Comment by KerballOne** [comment]
Okay, I cloned an instance with CKAN, removed ALL mods and their data.  
Then I installed ONLY the RP-1 Express, with the recommended mods.
This results in 97 mods total (compared with 204 for my previous setup).
Loaded the built in WAC-Corporal since it has several procedural parts.
Same issue.

The culprit is among the 97 mods that are INCLUDED with the RP-1 Express install.
![Screenshot 2024-05-29 165509](https://github.com/KSP-RO/RP-1/assets/161400249/d08385b5-9bfa-4c22-b34b-d59fac905357)


![Screenshot 2024-05-29 165550](https://github.com/KSP-RO/RP-1/assets/161400249/564d6926-db07-44d0-aacd-9fca45b973c0)

**Comment by siimav** [comment]
Welp, I truly have no idea what you did differently from the other hundreds of people who have never experienced this issue. Send ksp.log, I guess.

**Comment by KerballOne** [comment]
> Send ksp.log, I guess.

https://www.dropbox.com/scl/fo/pdffbe5mqvwxhlhhwpddn/AHpn8XpNSftvHAFIRaelNYY?rlkey=k7kfxmtfmog2aidpw33zvl4hr&st=akqm9pzy&dl=0

**Comment by siimav** [comment]
Can't say I see anything of interest in there. I'm not sure how we're going to figure out what makes your install special compared to the rest of us.

Does it happen with any vessels you put together yourself as well?

**Comment by KerballOne** [comment]
> Does it happen with any vessels you put together yourself as well?

Yes, I first noticed with a vessel I created from scratch using the early career guide for building sounding rockets. 
The issue is likely in procedural part, but triggered by KCT's simulator (not KRASH?).  



> what makes your install special compared to the rest of us

Are you able to reproduce using CKAN like I did?

**Comment by KerballOne** [comment]
Also noticed a ModuleManager error, don't know if it's relevant:
`30 errors related to GameData/SXT/Patches/ModCompatibility/SXT_TweakScale.cfg`

**Comment by Nazfib** [comment]
Those MM errors are caused by the (possibly empty) `TweakScale` directory that's still left in your GameData folder.
Could this be  a sign that you missed step §1.1 of the Install Guide?

**Comment by Capkirk123** [comment]
That is very relevant, MM errors can indicate a serious issue and should not occur if the mod is installed correctly. I would suggest removing _all_ mods and starting over with a fresh reinstall.

**Comment by KerballOne** [comment]
> Those MM errors
> That is very relevant, MM errors can indicate a serious issue

I cleared the GameData folder and PartDatabase of all mods (except for squad stuff), now I get no MM errors.  It's clear.  ModuleManager was not indicating the culprit :(
Still, the same problem.

**Comment by KerballOne** [comment]
Okay, nuked from orbit.  Uninstalled the entire KSP game from the Steam menu, wiped the entire Kerbal Space Program directory, and reinstalled as a virgin install.  
I don't know what it was, but apparently something was hiding outside of the GameData folder.

It works now.
![Screenshot 2024-05-29 215323](https://github.com/KSP-RO/RP-1/assets/161400249/e980a655-08b7-4cf6-a4c9-433f4988da3f)
