### ISSUE TITLE
Hiring staff buggy

### ISSUE THREAD

**Issue by asymptoto** [KSP-RO/RP-1#2378]
I've found a very weird bug with the staff window. Whenever I try to buy researchers, the count is immediately reset back to the original number. Also, when I buy engineers, they are subtracted from my researchers and I'm fairly certain I've had exactly 1k researchers before. I have included a GIF of the issue and the savefile in question. I am currently on version 3.8.0.0.
![Weird](https://github.com/KSP-RO/RP-1/assets/35931653/5192a2e7-05d7-4f51-baea-b42ec80ed787)
[Save.zip](https://github.com/user-attachments/files/15793877/Save.zip)

**Comment by asymptoto** [comment]
Update: It seems to be related to the new auto-hire feature. I checked my last save before the bug occurred and the next event in the queue was "Reach 1000 researchers"

**Comment by siimav** [comment]
Was but no longer isn't? If you planned to hire 1000 then what did you do between that save and the issue starting happening?

**Comment by asymptoto** [comment]
I was at 994 and had an auto hire job to 1000. I didn't do much, at least nothing i would suspect to cause this. I think did an X-Plane mission, upgraded a launchpad, bought tooling/entry cost and worked on a vessel. However, I do recall the timer being buggy. It showed 0d, 00:00:-01 and didn't finish. I didn't think much of it and just warped to the next event manually and realized this bug after finishing work on a vessel. When I load the save the timer is fixed tho, so I doubt I can reproduce it

**Comment by asymptoto** [comment]
I found an older save with the bugged timer. At this stage it seems like the funds are subtracted correctly by the auto hire but the researchers are not added
[Quicksave44.zip](https://github.com/user-attachments/files/15795135/Quicksave44.zip)

**Comment by siimav** [comment]
Fixed in 39dc39398124e0ef07f6596aaadecc349e12cfc5
