### ISSUE TITLE
Repeatable early satellite contracts reset each other after completion?

### ISSUE THREAD

**Issue by kretze** [KSP-RO/RP-1#2436]
It concerns
Commercial Communications Satellite (Early) and Commercial Navigation Satellite (Early)

After the navigation sat contract was completed, the rewards and times were as follows.

Commercial Communications Satellite (Early)
![image](https://github.com/user-attachments/assets/9bfd1540-0dd6-4703-bdc3-f1cf37f1e74b)

Commercial Navigation Satellite (Early)
![image](https://github.com/user-attachments/assets/d12f2a6a-40b9-4d9d-85f8-94dc5eac0a00)

After fast forwarding 24 hours, the communication sat contract was reset to the value of the navigation sat contract.

Commercial Communications Satellite (Early)
![image](https://github.com/user-attachments/assets/5771fae9-2f6c-475a-ac6b-8727e8862d0a)

Commercial Navigation Satellite (Early)
![image](https://github.com/user-attachments/assets/20ad1718-2fc6-45da-91df-2a6919bc4a4e)

**Comment by kretze** [comment]
I'm not entirely sure, but could this be the error?
Comsat variables are used in the navsat config.


GameData/RP-1/Contracts/Commercial Applications 1/EarlyNavSat-CA.cfg
Line 7     description
![image](https://github.com/user-attachments/assets/fad33a5d-fcaa-4c5b-8efb-d6fc6d370593)

![image](https://github.com/user-attachments/assets/ab9056b9-967a-4f19-a45e-fa8580162908)

**Comment by kretze** [comment]
I have put together a summary of the contracts from the save games.
Maybe that will help narrow it down.

Text files with contract infos from save and summary
https://drive.google.com/drive/folders/1eItTQjKb6xj9xxpbPNyIscChF8kBGmrv?usp=sharing

**Comment by Capkirk123** [comment]
This is intended behavior
