### ISSUE TITLE
PARTUPGRADES for Tanks

### ISSUE THREAD

**Issue by pap1723** [KSP-RO/RP-1#930]
As it is currently constructed, Fuel Tanks with the new system improve their mass-ratio and the utilization amounts for the tanks. However, each version of the tanks are more expensive than the previous version which makes sense as the new technology is developed. Eventually, the cost of these tanks should come down as they are better developed and the machining processes are improved.

I propose making PARTUPGRADES for Tanks that will work as cost reducers (and any other ideas you may have, mass-ratio, utilization, etc) in order to improve the value of the tanks.

**Comment by Bornholio** [comment]
Tech nodes (Carbon Fiber '68-74), (High Strength CF '88), Industrial CF '90's. Post 2000 cheap but lower performance CF is readily available (sports gear etc.) I've used the stuff from a mfg that does hockey sticks for robot structural pretty cost effective.  

Advanced composites in mid 90's, COPV's have really come in to full use in post 2000 especially for pressurants and RCS fuels https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20050031227.pdf

 Advanced aluminum Alloys in 70 and 80s should lower cost. Russian vanadium and other aerospace alloys.

  Al-Li is a big advance for post 2000 but it costs a bunch more both for material (x3ish) and fabrication (only friction stir welding)

Aerogel is now starting to move into final research stages and may augment MLI in the near future in addition giving more temp resistance to the tank overall .  Even commercial relatively cheap aerogel is now available
https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20180006720.pdf

Near future glass microbeads are getting the boiloff problems closer to solved https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20180006604.pdf

**Comment by NathanKell** [comment]
We now have PARTUPGRADEs for tanks.
