### ISSUE TITLE
Premade satellites for satellite contracts. 

### ISSUE THREAD

**Issue by Builderbast** [KSP-RO/RP-1#951]
Right now, satellite contracts are mostly based on designing a satellite and launching into a given orbit, Theoretically, you can make them as simple, cheap, and lightweight as you want. The current fix to this is payloads, which are put in fuel tanks to simulate the mass of that spacecraft. This does often result in bulky, ugly, and most of all repetitive satellites. What if you, instead of making your own collection of payload-filled tanks and shooting it into orbit, you could launch pre-made, realistic satellites to orbit? 

The idea is to make a lot of one part satellites. These would be custom made satellites, and can be of any mass, size, shape and complexity. Satellite contracts could then be altered to ask you to bring that part to any given orbit. 

These contracts could then also require you to have more different satellites on board. 

Examples of such one-part satellites are those from Raidernicks Us-probes pack, but more, especially modern satellites would be needed. 

I think this would really make satellite contracts more fun and realistic then ever before.

**Comment by leudaimon** [comment]
One more simple way to tackle this, would be to add a collection of one-part satellites which are an empty shell with a service module tank or some dedicated payload tank. Then you can add the required amount of payload to this part and complete the contract with a nice sat instead of a tank.

**Comment by m4gus88** [comment]
If the problem is that the satellites become big and bulky, maybe the easiest solution is to increase the unit mass of the payload resources, and decrease the amount required by the contracts. That way you'll get the same payout for a smaller satellite while keeping the same mass.

**Comment by pianojosh** [comment]
I could see going even further here. To accommodate miniaturization over time, don't let the ComSat, NavSat, and WeatherSat payloads be in any tank *except* the pre-made satellite parts. And, over time, unlock satellite buses that have larger payload capacities for the same physical size.

**Comment by siimav** [comment]
Shipped.
